base = "positions::forest"

[[rulesets]]
name = "singular"
[rulesets.rules]
"acolyte" = "수행사제"
"diplomat" = "외교관"
"druid" = "드루이드"
"princess" = "공주"
"queen" = "여왕"
"ranger captain" = "레인저 대장"

[[rulesets]]
name = "plural"
[rulesets.rules]
"acolytes" = "수행사제"
"diplomats" = "외교관"
"druids" = "드루이드"
"princesses" = "공주"
"queens" = "여왕"
"ranger captains" = "레인저 대장"
