base = "positions::mountain"

[[rulesets]]
name = "singular"
[rulesets.rules]
"monarch" = "군주"
"general" = "장군"
"lieutenant" = "중위"
"captain" = "대장"
"militia commander" = "민병대 지휘관"
"militia captain" = "민병대 대장"
"sheriff" = "치안관"
"captain of the guard" = "경비대장"
"expedition leader" = "원정대장"
"mayor" = "시장"
"manager" = "관리인"
"chief medical dwarf" = "수석 드워프 의사"
"broker" = "중개인"
"bookkeeper" = "장부지기"
"outpost liaison" = "전초기지 연락관"
"diplomat" = "외교관"
"duke" = "공작"
"count" = "백작"
"baron" = "남작"
"champion" = "챔피언"
"hammerer" = "망치 형벌관"
"dungeon master" = "지하감옥장"
"administrator" = "관리자"
"messenger" = "전령"

[[rulesets]]
name = "plural"
[rulesets.rules]
"monarchs" = "군주"
"generals" = "장군"
"lieutenants" = "중위"
"captains" = "대장"
"militia commanders" = "민병대 지휘관"
"militia captains" = "민병대 대장"
"sheriffs" = "치안관"
"captains of the guard" = "경비대장"
"expedition leaders" = "원정대장"
"mayors" = "시장"
"managers" = "관리인"
"chief medical dwarves" = "수석 드워프 의사"
"brokers" = "중개인"
"bookkeepers" = "장부지기"
"outpost liaisons" = "전초기지 연락관"
"diplomats" = "외교관"
"dukes" = "공작"
"counts" = "백작"
"barons" = "남작"
"champions" = "챔피언"
"hammerers" = "망치 형벌관"
"dungeon masters" = "지하감옥장"
"administrators" = "관리자"
"messengers" = "전령"
