base = "materials::state"

[[rulesets]]
[rulesets.rules]
"gold dust" = "금가루"
"metal" = "금속"
"native gold dust" = "천연 금가루"
"fat" = "지방"
"grease" = "유지"
"cartilage" = "연골"
"cheese" = "치즈"
"wood" = "목재"
"sponge" = "해면"
"saguaro rib wood" = "사구아로 갈빗대 목재"
"oak" = "참나무"
"birch" = "자작나무"
"{shared}" = "{shared}"

[[rulesets]]
name = "adjective"
[rulesets.rules]
"fatty" = "지방질"
"greasy" = "기름진"
"cartilaginous" = "연골질"
"cheesy" = "치즈"
"wooden" = "목제"
"spongy" = "해면질"
"saguaro rib" = "사구아로 갈빗대"
"oaken" = "참나무제"
"birchen" = "자작나무제"
"ashen" = "물푸레나무제"
"{shared}" = "{shared}"

[[rulesets]]
name = "shared"
[rulesets.rules]
"{shared::^0}{shared::main}{shared::$0}" = "{shared::^0}{shared::main}{shared::$0}"

[[rulesets]]
name = "shared::^0"
optional = true
[rulesets.rules]
"boiling " = "끓는 "
"ground " = "분쇄된 "
"pressed " = "압착된 "
"molten " = "용융된 "
"frozen " = "얼어붙은 "
"melted " = "녹은 "

[[rulesets]]
name = "shared::main"
[rulesets.rules]
"acacia" = "아카시아"
"adamantine" = "아다만틴"
"adder man venom" = "살무사인간 독"
"adder venom" = "살무사 독"
"alabaster" = "설화석고"
"alder" = "오리나무"
"alexandrite" = "알렉산드라이트"
"almandine" = "알만딘"
"almond wood" = "아몬드 목재"
"alpaca cheese" = "알파카 치즈"
"alpaca's milk" = "알파카 우유"
"aluminum" = "알루미늄"
"alunite" = "명반석"
"amber" = "호박"
"amber opal" = "호박 오팔"
"amethyst" = "자수정"
"andesite" = "안산암"
"anhydrite" = "경석고"
"antler" = "사슴뿔"
"apple cider" = "사과 사이더"
"apple wood" = "사과나무 목재"
"apricot wine" = "살구 와인"
"apricot wood" = "살구나무 목재"
"aquamarine" = "아쿠아마린"
"artichoke wine" = "아티초크 와인"
"ash" = "재"
"ash glaze" = "재유약"
"aventurine" = "사금석"
"avocado wood" = "아보카도나무 목재"
"banana beer" = "바나나 맥주"
"banded agate" = "줄무늬 마노"
"bandfire opal" = "불무늬 오팔"
"bark scorpion man venom" = "나무껍질전갈인 독소"
"bark scorpion venom" = "나무껍질전갈 독소"
"barley flour" = "보리가루"
"barley wine" = "보리 와인"
"basalt" = "현무암"
"bauxite" = "보크사이트"
"bayberry wine" = "양매 와인"
"bayberry wood" = "양매나무 목재"
"beetroot wine" = "비트 뿌리 와인"
"bilberry wine" = "빌베리 와인"
"billon" = "빌론 합금"
"bismuth" = "비스무트"
"bismuth bronze" = "비스무트 청동"
"bismuthinite" = "휘비스무트광"
"bitter orange wood" = "쓴오렌지나무 목재"
"bituminous coal" = "역청탄"
"blackberry wine" = "블랙베리 와인"
"black bronze" = "흑청동"
"black-cap" = "검은갓버섯"
"black diamond" = "검은 다이아몬드"
"black mamba man venom" = "블랙맘바뱀인 독소"
"black mamba venom" = "블랙맘바 독소"
"black opal" = "검은 오팔"
"black pyrope" = "검은 파이로프"
"black sand" = "검은 모래"
"black zircon" = "검은 지르콘"
"blood" = "피"
"blood amaranth beer" = "피비름 맥주"
"blood amaranth flour" = "피비름가루"
"bloodstone" = "혈석"
"blood thorn" = "피가시"
"blueberry wine" = "블루베리 와인"
"blue diamond" = "파란 다이아몬드"
"blue garnet" = "파란 가넷"
"blue jade" = "파란 비취"
"bone" = "뼈"
"bone meal" = "뼛가루"
"bone opal" = "골질 오팔"
"borax" = "붕사"
"brain" = "뇌"
"brass" = "황동"
"brimstone" = "유황"
"bronze" = "청동"
"brown jasper" = "갈색 벽옥"
"brown recluse spider man venom" = "갈색 은둔거미인 독소"
"brown recluse spider venom" = "갈색 은둔거미 독소"
"brown zircon" = "갈색 지르콘"
"buckwheat beer" = "메밀 맥주"
"buckwheat flour" = "메밀가루"
"bud" = "꽃봉오리"
"bumblebee honey" = "호박벌 꿀"
"bumblebee mead" = "호박벌 꿀술"
"bumblebee royal jelly" = "호박벌 로열젤리"
"bumblebee venom" = "호박벌 독소"
"bumblebee wax" = "호박벌 밀랍"
"bumblebee wax cake" = "호박벌 밀랍 케이크"
"bushmaster man venom" = "부시마스터인 독소"
"bushmaster venom" = "부시마스터 독소"
"cacao wood" = "카카오나무"
"calcareous ooze" = "석회질 연니"
"calcite" = "방해석"
"candlenut" = "캔들넛"
"carambola wine" = "카람볼라 와인"
"carambola wood" = "카람볼라나무"
"carnelian" = "홍옥수"
"carrot wine" = "당근 와인"
"cashew wood" = "캐슈나무"
"cassava beer" = "카사바 맥주"
"cassiterite" = "주석석"
"cat's eye" = "묘안석"
"cave blob fluid" = "동굴 점액덩어리 체액"
"cave floater gas" = "동굴 부유자 가스"
"cave floater juice" = "동굴 부유자 즙"
"cave spider venom" = "동굴 거미 독소"
"cedar" = "삼나무"
"chalk" = "백악암"
"cherry opal" = "체리 오팔"
"cherry wine" = "체리 와인"
"cherry wood" = "체리나무"
"chert" = "각암"
"chestnut" = "밤나무"
"chitin" = "키틴"
"chromite" = "크롬철광"
"chrysoberyl" = "금록석"
"chrysocolla" = "규공작석"
"chrysoprase" = "녹옥수"
"cinnabar" = "진사"
"cinnamon grossular" = "시나몬그로슐라"
"citrine" = "황수정"
"citron wood" = "시트론나무"
"claro opal" = "스모키 오팔"
"clay" = "점토"
"clay loam" = "점토질 양토"
"claystone" = "점토암"
"clear diamond" = "무색 다이아몬드"
"clear garnet" = "투명 석류석"
"clear glass" = "투명 유리"
"clear tourmaline" = "투명 전기석"
"clear zircon" = "투명 지르콘"
"coal" = "석탄"
"coal slush" = "석탄 찌꺼기"
"cobaltite" = "코발타이트"
"coconut palm" = "코코넛야자"
"coffee wood" = "커피나무"
"condensed iron man gas" = "농축 철인 가스"
"conglomerate" = "역암"
"copper" = "구리"
"copperhead snake man venom" = "구리머리살무사인 독소"
"copperhead snake venom" = "구리머리살무사 독소"
"coral" = "산호"
"corrupted blood" = "부패한 피"
"cotton" = "목화"
"cotton seed" = "목화 씨앗"
"cottonseed oil" = "목화씨 기름"
"cottonseed oil soap" = "목화씨 기름 비누"
"cow cheese" = "암소 치즈"
"cow's milk" = "암소 우유"
"cranberry wine" = "크랜베리 와인"
"cryolite" = "빙정석"
"crystal glass" = "크리스탈 유리"
"crystal opal" = "크리스탈 오팔"
"custard-apple cider" = "커스터드애플 사이더"
"custard-apple wood" = "커스터드애플나무"
"cuttlefish ink" = "갑오징어 먹물"
"cuttlefish man ink" = "갑오징어인 먹물"
"dacite" = "영안암"
"date palm wood" = "대추야자"
"date wine" = "대추야자 와인"
"demantoid" = "데만토이드"
"dendritic agate" = "가지무늬 마노"
"desert lime wood" = "사막라임나무"
"dimple dye" = "딤플컵 염료"
"diorite" = "섬록암"
"dirt" = "흙"
"dolomite" = "백운석"
"donkey cheese" = "당나귀 치즈"
"donkey's milk" = "당나귀 우유"
"durian wine" = "두리안 와인"
"durian wood" = "두리안 목재"
"dwarven ale" = "드워프 에일"
"dwarven beer" = "드워프 맥주"
"dwarven cheese" = "드워프 치즈"
"dwarven milk" = "드워프 우유"
"dwarven rum" = "드워프 럼"
"dwarven sugar" = "드워프 설탕"
"dwarven syrup" = "드워프 시럽"
"dwarven wheat flour" = "드워프 밀가루"
"dwarven wine" = "드워프 와인"
"earthenware" = "토기"
"eggshell" = "달걀 껍데기"
"egg white" = "달걀 흰자"
"egg yolk" = "달걀 노른자"
"electrum" = "호박금"
"emerald" = "에메랄드"
"emerald dye" = "에메랄드 염료"
"eye tissue" = "안구 조직"
"faint yellow diamond" = "희미한 노란 다이아몬드"
"feather" = "깃털"
"feather wood" = "깃털나무 목재"
"fiber" = "섬유"
"filth" = "오물"
"filth slush" = "오물 진흙"
"fine pewter" = "정제 백랍"
"finger lime wood" = "핑거 라임 목재"
"finger millet beer" = "핑거 밀릿 맥주"
"finger millet flour" = "핑거 밀릿 가루"
"fire agate" = "파이어 마노"
"fire clay" = "내화 점토"
"fire opal" = "파이어 오팔"
"fisher berry wine" = "피셔 베리 와인"
"flames" = "화염"
"flax flour" = "아마 가루"
"flax seed" = "아마씨"
"flesh" = "살점"
"flower" = "꽃"
"fluff" = "솜털"
"fonio beer" = "포니오 맥주"
"fonio flour" = "포니오 가루"
"fortification agate" = "성벽 마노"
"foxtail millet beer" = "폭스테일 밀릿 맥주"
"foxtail millet flour" = "폭스테일 밀릿 가루"
"fruit" = "열매"
"fungiwood" = "진균 목재"
"fur" = "모피"
"gabbro" = "반려암"
"galena" = "방연석"
"garnierite" = "가르니에라이트"
"giant adder venom" = "거대 살무사 독소"
"giant bark scorpion venom" = "거대 나무껍질전갈 독소"
"giant black mamba venom" = "거대 블랙맘바 독소"
"giant brown recluse spider venom" = "거대 갈색은둔거미 독소"
"giant bushmaster venom" = "거대 부시마스터 독소"
"giant cave spider venom" = "거대 동굴거미 독소"
"giant copperhead snake venom" = "거대 구리머리살무사 독소"
"giant cuttlefish ink" = "거대 갑오징어 먹물"
"giant gila monster venom" = "거대 길라몬스터 독소"
"giant kangaroo cheese" = "거대 캥거루 치즈"
"giant kangaroo's milk" = "거대 캥거루 젖"
"giant king cobra venom" = "거대 킹코브라 독소"
"giant octopus ink" = "거대 문어 먹물"
"giant one-humped camel cheese" = "거대 단봉낙타 치즈"
"giant one-humped camel's milk" = "거대 단봉낙타 젖"
"giant platypus venom" = "거대 오리너구리 독소"
"giant rattlesnake venom" = "거대 방울뱀 독소"
"giant squid ink" = "거대 오징어 먹물"
"giant tapir cheese" = "거대 맥 치즈"
"giant tapir's milk" = "거대 맥 젖"
"giant two-humped camel cheese" = "거대 쌍봉낙타 치즈"
"giant two-humped camel's milk" = "거대 쌍봉낙타 젖"
"gila monster man venom" = "길라몬스터맨 독소"
"gila monster venom" = "길라몬스터 독소"
"ginkgo wood" = "은행나무"
"gizzard tissue" = "모래주머니 조직"
"glumprong" = "자영나무"
"gneiss" = "편마암"
"gnomeblight" = "노움마름병"
"goat cheese" = "염소 치즈"
"goat's milk" = "염소 젖"
"goblin-cap" = "고블린갓버섯"
"gold" = "금"
"golden beryl" = "금주석"
"golden salve" = "금색 연고"
"gold opal" = "금 오팔"
"goo" = "끈적한 피"
"goshenite" = "백주석"
"granite" = "화강암"
"graphite" = "흑연"
"gray chalcedony" = "회색 옥수"
"green diamond" = "녹색 다이아몬드"
"green glass" = "녹색 유리"
"green jade" = "녹색 비취"
"green tourmaline" = "녹색 토르말린"
"green zircon" = "녹색 지르콘"
"grime" = "때"
"guava wine" = "구아바 와인"
"guava wood" = "구아바나무"
"gut" = "창자"
"gutter cruor" = "응혈주"
"gypsum" = "석고"
"gypsum plaster" = "석고 회반죽"
"hair" = "모발"
"hard wheat beer" = "경질밀 맥주"
"hard wheat flour" = "경질밀 가루"
"harlequin opal" = "할리퀸 오팔"
"hazel wood" = "헤이즐나무"
"heart tissue" = "심장 조직"
"heliodor" = "헬리오도르"
"helmet snake venom" = "투구뱀 독소"
"hematite" = "적철광"
"hemp" = "대마"
"hemp flour" = "대마 가루"
"hemp seed" = "대마 씨앗"
"hempseed oil" = "대마씨유"
"hempseed oil soap" = "대마씨유 비누"
"highwood" = "하이우드"
"honey bee honey" = "벌꿀"
"honey bee royal jelly" = "로열젤리"
"honey bee venom" = "벌 독소"
"honey bee wax" = "밀랍"
"honey bee wax cake" = "밀랍 케이크"
"honey yellow beryl" = "꿀빛 녹주석"
"hoof" = "발굽"
"horn" = "뿔"
"hornblende" = "각섬석"
"horn silver" = "각은광"
"horse cheese" = "말젖 치즈"
"horse's milk" = "말젖"
"ice" = "얼음"
"ichor" = "체액"
"ilmenite" = "티탄철석"
"indigo tourmaline" = "남색 토르말린"
"iron" = "철"
"iron man gas" = "철인 기체"
"ivory" = "상아"
"jasper opal" = "재스퍼 오팔"
"jelly opal" = "젤리 오팔"
"jet" = "흑옥"
"jute" = "황마 섬유"
"kangaroo cheese" = "캥거루 치즈"
"kangaroo man cheese" = "캥거루인 치즈"
"kangaroo man's milk" = "캥거루인 젖"
"kangaroo's milk" = "캥거루 젖"
"kaniwa beer" = "카니와 맥주"
"kaniwa flour" = "카니와 가루"
"kaolinite" = "고령석"
"kapok" = "목면나무"
"kenaf" = "케나프"
"kenaf seed" = "양마 씨앗"
"kenaf seed oil" = "양마 씨앗 기름"
"kenaf seed oil soap" = "양마 씨앗 기름 비누"
"kidney tissue" = "신장 조직"
"kimberlite" = "킴벌라이트"
"king cobra man venom" = "킹코브라 인간 독액"
"king cobra venom" = "킹코브라 독액"
"kumquat wood" = "금귤 목재"
"kunzite" = "쿤자이트"
"lace agate" = "레이스 마노"
"lapis lazuli" = "청금석"
"larch" = "낙엽송"
"lavender jade" = "라벤더 비취"
"lay pewter" = "저급 백랍"
"lead" = "납"
"leaf" = "잎"
"leather" = "가죽"
"levin opal" = "번개 오팔"
"light yellow diamond" = "밝은 노란 다이아몬드"
"lignite" = "갈탄"
"limestone" = "석회암"
"lime wood" = "라임 목재"
"limonite" = "갈철석"
"linen" = "아마 섬유"
"linseed oil" = "아마씨 기름"
"linseed oil soap" = "아마씨 기름 비누"
"liquid fire" = "액체 화염"
"liver tissue" = "간 조직"
"llama cheese" = "라마 치즈"
"llama's milk" = "라마 우유"
"loam" = "양토"
"loamy sand" = "양질사토"
"Longland beer" = "롱랜드 맥주"
"Longland flour" = "롱랜드 가루"
"lung tissue" = "폐 조직"
"lychee wine" = "리치 와인"
"lychee wood" = "리치 목재"
"lye" = "잿물"
"lye slush" = "잿물 슬러시"
"macadamia wood" = "마카다미아 목재"
"magma" = "마그마"
"magnetite" = "자철석"
"mahogany" = "마호가니"
"maize beer" = "옥수수 맥주"
"maize flour" = "옥수수 가루"
"malachite" = "공작석"
"mango wine" = "망고 와인"
"mango wood" = "망고 목재"
"mangrove" = "맹그로브"
"maple" = "단풍나무"
"marble" = "대리석"
"marcasite" = "백철석"
"mead" = "벌꿀주"
"melanite" = "흑석류석"
"mica" = "운모"
"microcline" = "미사장석"
"milk of lime" = "석회유"
"milk opal" = "유백오팔"
"milk quartz" = "유백석영"
"mog juice" = "톡토기 육즙"
"moonstone" = "월장석"
"morganite" = "모르가나이트"
"morion" = "흑수정"
"moss agate" = "이끼마노"
"moss opal" = "이끼오팔"
"mud" = "진흙"
"mudstone" = "이암"
"muscle" = "근육"
"mushroom" = "버섯"
"nail" = "손톱"
"native aluminum" = "자연 알루미늄"
"native copper" = "자연 구리"
"native gold" = "자연 금"
"native platinum" = "자연 백금"
"native silver" = "자연 은"
"nervous tissue" = "신경 조직"
"nether-cap" = "네더버섯"
"nickel" = "니켈"
"nickel silver" = "니켈은"
"oat flour" = "귀리 가루"
"obsidian" = "흑요석"
"octopus ink" = "문어 먹물"
"octopus man ink" = "문어인 먹물"
"olive fruit" = "올리브 열매"
"olive oil" = "올리브유"
"olive oil soap" = "올리브유 비누"
"olive pomace" = "올리브 찌꺼기"
"olive wood" = "올리브 나무"
"olivine" = "감람석"
"one-humped camel cheese" = "단봉낙타 치즈"
"one-humped camel man cheese" = "단봉낙타인 치즈"
"one-humped camel man's milk" = "단봉낙타인 젖"
"one-humped camel's milk" = "단봉낙타 젖"
"onyx" = "오닉스"
"onyx opal" = "오닉스 오팔"
"orange wood" = "오렌지 나무"
"orpiment" = "웅황"
"orthoclase" = "정장석"
"pancreatic tissue" = "췌장 조직"
"papaya wine" = "파파야주"
"papaya wood" = "파파야나무목재"
"papyrus" = "파피루스"
"paradise nut wood" = "파라다이스너트나무목재"
"parchment" = "양피지"
"parsnip wine" = "파스닙와인"
"passion fruit wine" = "패션프루트와인"
"peach cider" = "복숭아사이더"
"peach wood" = "복숭아나무목재"
"pearlash" = "진주회"
"pearl millet beer" = "진주조맥주"
"pearl millet flour" = "진주조가루"
"pear wood" = "배나무목재"
"peat" = "이탄"
"pecan wood" = "피칸나무목재"
"pelagic clay" = "심해점토"
"pendant amaranth beer" = "늘어진비름맥주"
"pendant amaranth flour" = "늘어진비름가루"
"periclase" = "페리클라스"
"peridot" = "감람석"
"perry" = "배사이더"
"persimmon wine" = "감와인"
"persimmon wood" = "감나무목재"
"petrified wood" = "석화목"
"phantom spider venom" = "환영거미독소"
"phyllite" = "천매암"
"picture jasper" = "그림 벽옥"
"pig cheese" = "집돼지치즈"
"pig iron" = "선철"
"pig's milk" = "집돼지젖"
"pig tail" = "돼지꼬리풀"
"pine" = "소나무"
"pineapple opal" = "파인애플오팔"
"pineapple wine" = "파인애플와인"
"pinfire opal" = "핀파이어 오팔"
"pink garnet" = "분홍가넷"
"pink jade" = "분홍 비취"
"pink tourmaline" = "분홍토르말린"
"pipe opal" = "파이프오팔"
"pitchblende" = "역청우라늄광"
"plant" = "식물"
"platinum" = "백금"
"platypus man venom" = "오리너구리인간독소"
"platypus venom" = "오리너구리독소"
"plume agate" = "깃털 마노"
"plump helmet man tissue" = "통통투구버섯인간조직"
"plum wine" = "자두와인"
"plum wood" = "자두나무목재"
"pomegranate wine" = "석류와인"
"pomegranate wood" = "석류나무목재"
"pomelo wood" = "포멜로나무목재"
"porcelain" = "자기"
"potash" = "가리"
"potash slush" = "가리 찌꺼기"
"potato wine" = "감자 와인"
"prase" = "청록 석영"
"prase opal" = "청록 오팔"
"precious fire opal" = "귀한 불 오팔"
"prickle berry wine" = "가시딸기 와인"
"puddingstone" = "푸딩암"
"pudge" = "지방 덩어리"
"purple amaranth beer" = "자색비름 맥주"
"purple amaranth flour" = "자색비름 가루"
"purple spinel" = "자색 첨정석"
"pus" = "고름"
"pyrite" = "황철석"
"pyrolusite" = "연망간광"
"quartzite" = "석영암"
"quicklime" = "생석회"
"quinoa beer" = "퀴노아 맥주"
"quinoa flour" = "퀴노아 가루"
"radish wine" = "래디시 와인"
"rambutan wine" = "람부탄 와인"
"rambutan wood" = "람부탄 나무"
"ramie" = "모시풀"
"raspberry wine" = "라즈베리 와인"
"rattlesnake man venom" = "방울뱀 인간 독소"
"rattlesnake venom" = "방울뱀 독소"
"raw adamantine" = "원시 정금"
"realgar" = "웅황"
"red beryl" = "홍주석"
"red diamond" = "붉은 다이아몬드"
"red flash opal" = "붉은 섬광 오팔"
"red grossular" = "붉은 석류석"
"red pyrope" = "적 석류석"
"redroot dye" = "붉은뿌리 염료"
"red sand" = "붉은 모래"
"red spinel" = "붉은 첨정석"
"red tourmaline" = "붉은 전기석"
"red zircon" = "붉은 지르콘"
"reindeer cheese" = "순록 치즈"
"reindeer's milk" = "순록 우유"
"resin opal" = "수지광 오팔"
"rhodolite" = "주홍 석류석"
"rhyolite" = "유문암"
"rice beer" = "쌀 맥주"
"rice flour" = "쌀 가루"
"river spirits" = "하천 독주"
"rock" = "암석"
"rock crystal" = "바위 수정"
"rock nut" = "바위 견과"
"rock nut oil" = "바위견과 기름"
"rock nut soap" = "바위견과 비누"
"rock salt" = "암염"
"rope reed" = "밧줄 갈대"
"rose gold" = "로즈 골드"
"rose quartz" = "장미석영"
"round lime wood" = "둥근 라임 목재"
"rubber wood" = "고무나무 목재"
"rubicelle" = "주황색 스피넬"
"ruby" = "루비"
"rutile" = "금홍석"
"rye beer" = "호밀 맥주"
"rye flour" = "호밀가루"
"salt" = "소금"
"saltpeter" = "초석"
"sand" = "모래"
"sand pear cider" = "모래배 사이더"
"sand pear wood" = "모래배 목재"
"sandstone" = "사암"
"sandy clay" = "사질 점토"
"sandy clay loam" = "사질 식양토"
"sandy loam" = "사질 양토"
"sapphire" = "사파이어"
"sard" = "갈옥수"
"sardonyx" = "사도닉스"
"satinspar" = "섬유석고"
"scale" = "비늘"
"schist" = "편암"
"schorl" = "흑전기석"
"seed" = "씨앗"
"selenite" = "투명석고"
"serpentine" = "사문석"
"serpent man venom" = "독사인 독소"
"sewer brew" = "하수구 명주"
"shale" = "혈암"
"sheep cheese" = "양 치즈"
"sheep's milk" = "양젖"
"shell" = "껍데기"
"shell opal" = "조개 오팔"
"siliceous ooze" = "규질 진흙"
"silk" = "비단"
"silt" = "실트"
"silt loam" = "실트질 양토"
"siltstone" = "실트암"
"silty clay" = "실트질 점토"
"silty clay loam" = "실트질 식양토"
"silver" = "은"
"sinew" = "힘줄"
"single-grain wheat beer" = "외알밀 맥주"
"single-grain wheat flour" = "외알밀가루"
"skin" = "피부"
"slade" = "기반암"
"slate" = "점판암"
"sliver dye" = "갈라진 갈고리 염료"
"slush" = "진흙땅"
"smoky quartz" = "연수정"
"snow" = "눈"
"soap" = "비누"
"soft wheat beer" = "연질 밀 맥주"
"soft wheat flour" = "연질 밀가루"
"sorghum beer" = "수수 맥주"
"sorghum flour" = "수수가루"
"spelt beer" = "스펠트 밀 맥주"
"spelt flour" = "스펠트 밀가루"
"sphalerite" = "섬아연광"
"spine" = "척추"
"spit" = "침"
"spleen tissue" = "비장 조직"
"spore tree" = "포자나무"
"squid ink" = "오징어 먹물"
"squid man ink" = "오징어 인간 먹물"
"star ruby" = "스타 루비"
"star sapphire" = "스타 사파이어"
"steam" = "증기"
"steel" = "강철"
"sterling silver" = "스털링 실버"
"stibnite" = "휘안석"
"stomach tissue" = "위 조직"
"stoneware" = "석기"
"strawberry wine" = "딸기 와인"
"sunshine" = "일광주"
"sunstone" = "태양석"
"swamp whiskey" = "늪지 위스키"
"sweat" = "땀"
"sweet potato wine" = "고구마 와인"
"sylvite" = "실바이트"
"talc" = "활석"
"tallow" = "동물 지방"
"tanzanite" = "탄자나이트"
"tapir cheese" = "맥 치즈"
"tapir man cheese" = "맥인 치즈"
"tapir man's milk" = "맥인 우유"
"tapir's milk" = "맥 우유"
"tears" = "눈물"
"tea wood" = "차나무 목재"
"teff beer" = "테프 맥주"
"teff flour" = "테프가루"
"tetrahedrite" = "사면동광"
"tigereye" = "호안석"
"tiger iron" = "호철석"
"tin" = "주석"
"tin glaze" = "주석 유약"
"tomatillo wine" = "토마틸로 와인"
"tomato wine" = "토마토 와인"
"tooth" = "이빨"
"topaz" = "토파즈"
"topazolite" = "토파졸라이트"
"tower-cap" = "탑버섯"
"trifle pewter" = "값싼 백랍"
"tsavorite" = "차보라이트"
"tube agate" = "관맥 마노"
"tuber beer" = "덩이줄기 맥주"
"tunnel tube" = "터널관균"
"turnip wine" = "순무 와인"
"turquoise" = "터키석"
"two-grain wheat beer" = "두알밀 맥주"
"two-grain wheat flour" = "두알밀 밀가루"
"two-humped camel cheese" = "쌍봉낙타 치즈"
"two-humped camel man cheese" = "쌍봉낙타인 치즈"
"two-humped camel man's milk" = "쌍봉낙타인 젖"
"two-humped camel's milk" = "쌍봉낙타 젖"
"unknown boiling creature substance" = "알 수 없는 끓는 생물질"
"unknown boiling plant substance" = "알 수 없는 끓는 식물 유래물"
"unknown boiling substance" = "알 수 없는 끓는 물질"
"unknown creature" = "알 수 없는 생물"
"unknown creature substance" = "알 수 없는 생물질"
"unknown frozen" = "알 수 없는 얼어붙은 것"
"unknown frozen creature" = "알 수 없는 얼어붙은 생물"
"unknown frozen creature substance" = "알 수 없는 얼어붙은 생물질"
"unknown frozen plant" = "알 수 없는 얼어붙은 식물"
"unknown frozen plant substance" = "알 수 없는 얼어붙은 식물 유래물"
"unknown frozen substance" = "알 수 없는 얼어붙은 물질"
"unknown plant substance" = "알 수 없는 식물 유래물"
"unknown pressed frozen creature substance" = "알 수 없는 압착된 얼어붙은 생물질"
"unknown pressed frozen plant substance" = "알 수 없는 압착된 얼어붙은 식물 유래물"
"unknown slush" = "알 수 없는 오수"
"unknown substance" = "알 수 없는 물질"
"variscite" = "인알루미늄석"
"vellum" = "양피지"
"violet spessartine" = "보라색스페서타인"
"vomit" = "토사물"
"walnut wood" = "호두나무 목재"
"water" = "물"
"water buffalo cheese" = "물소 치즈"
"water buffalo's milk" = "물소 젖"
"wax opal" = "왁스 오팔"
"whip vine flour" = "채찍덩굴 가루"
"whip wine" = "채찍 와인"
"white chalcedony" = "백옥수"
"white jade" = "백비취"
"white millet beer" = "흰 조 맥주"
"white millet flour" = "흰 조 가루"
"white opal" = "흰 오팔"
"white sand" = "흰 모래"
"willow" = "버드나무"
"wine" = "포도주"
"wood opal" = "나무 오팔"
"wool" = "털실"
"yak cheese" = "야크 치즈"
"yak's milk" = "야크 우유"
"yellow diamond" = "노란 다이아몬드"
"yellow grossular" = "노란 그로슐라"
"yellow jasper" = "노란 벽옥"
"yellow sand" = "노란 모래"
"yellow spessartine" = "노란 스페사르타인"
"yellow zircon" = "노란 지르콘"
"zinc" = "아연"
"rusted metal" = "녹슨 금속"
"twisting metal" = "뒤틀린 금속"
"dark metal" = "어두운 금속"
"glowing metal" = "은은히 빛나는 금속"
"bright metal" = "밝은 금속"
"pale metal" = "창백한 금속"
"pock-marked metal" = "움푹 패인 금속"
"blistered metal" = "물집 난 금속"
"ruddy metal" = "붉그스름한 금속"
"flickering metal" = "깜박이는 금속"
"faceted metal" = "다면 금속"
"shining metal" = "빛나는 금속"
"flashing metal" = "번쩍이는 금속"
"translucent metal" = "반투명한 금속"
"frosty metal" = "성에 낀 금속"
"slick metal" = "매끈한 금속"
"singing metal" = "울리는 금속"
"black metal" = "검은 금속"
"multicolored metal" = "다채로운 금속"
"clear blue metal" = "짙푸른 금속"
"twinkling metal" = "반짝이는 금속"
"crashing metal" = "부서지는 금속"
"blazing metal" = "불타는 금속"
"booming metal" = "웅웅거리는 금속"
"searing metal" = "작열하는 금속"
"flowing metal" = "흐르는 금속"

[[rulesets]]
name = "shared::$0"
optional = true
[rulesets.rules]
" paste" = "페이스트"
" powder" = "분말"
" press cake" = "압착박"
" slurry" = "슬러리"
" paper" = "종이"
