base = "color"

[[rulesets]]
[rulesets.rules]
"{name}" = "{name}"

[[rulesets]]
name = "name"
[rulesets.rules]
"amber" = "호박색"
"amethyst" = "자수정색"
"apple green" = "애플 그린"
"aqua" = "아쿠아색"
"aquamarine" = "아쿠아마린색"
"ash gray" = "회백색"
"auburn" = "적갈색"
"azure" = "천청색"
"beige" = "베이지색"
"black" = "검은색"
"blue" = "파란색"
"blue-gray" = "청회색"
"brass" = "황동색"
"bright green" = "밝은 초록색"
"bronze" = "청동색"
"brown" = "갈색"
"buff" = "연한 황갈색"
"burnt sienna" = "번트 시에나색"
"burnt umber" = "번트 엄버색"
"cardinal" = "짙은 선홍색"
"carmine" = "연지홍"
"cerulean" = "세룰리안 파란색"
"charcoal" = "숯빛 회색"
"chartreuse" = "샤르트뢰즈 초록색"
"chestnut" = "밤색"
"chocolate" = "초콜릿색"
"cinnamon" = "계피색"
"clear" = "투명색"
"cobalt" = "코발트 파란색"
"copper" = "구리색"
"cornflower" = "수레국화 파란색"
"cream" = "크림색"
"crimson" = "진홍색"
"crocus purple" = "크로커스 보라색"
"dark azure" = "짙은 천청색"
"dark blue" = "짙은 파란색"
"dark brown" = "짙은 갈색"
"dark chestnut" = "짙은 밤색"
"dark green" = "짙은 초록색"
"dark indigo" = "짙은 남색"
"dark olive" = "짙은 올리브색"
"dark peach" = "짙은 복숭아색"
"dark pink" = "짙은 분홍색"
"dark scarlet" = "짙은 선홍색"
"dark tan" = "짙은 황갈색"
"dark violet" = "짙은 바이올렛색"
"deep sea blue" = "심해 파란색"
"ecru" = "미백색"
"eggplant" = "가지색"
"emerald" = "에메랄드색"
"eucalyptus" = "유칼립투스녹색"
"fern green" = "양치류녹색"
"flax" = "아마색"
"foxglove" = "폭스글러브보라"
"fuchsia" = "자홍색"
"glacier blue" = "빙하파랑"
"gold" = "금색"
"golden yellow" = "금황색"
"goldenrod" = "골든로드색"
"grass green" = "잔디녹색"
"gray" = "회색"
"green" = "녹색"
"green-yellow" = "황록색"
"heliotrope" = "헬리오트로프보라"
"indigo" = "남색"
"ivory" = "상아색"
"jade" = "비취색"
"lavender" = "라벤더색"
"lavender blush" = "라벤더블러시"
"leaf green" = "잎사귀녹색"
"lemon" = "레몬노랑"
"light blue" = "연파랑"
"light brown" = "연갈색"
"lilac" = "라일락색"
"lime" = "라임그린"
"mahogany" = "마호가니색"
"maroon" = "고동색"
"mauve" = "모브색"
"mauve taupe" = "모브토프색"
"midnight blue" = "미드나이트블루"
"mint green" = "민트그린"
"moss green" = "이끼녹색"
"ochre" = "황토색"
"olive" = "올리브색"
"orange" = "주황색"
"orchid pink" = "난초분홍"
"pale blue" = "옅은파랑"
"pale brown" = "옅은갈색"
"pale chestnut" = "옅은밤색"
"pale pink" = "연분홍색"
"peach" = "복숭아색"
"pearl" = "진주색"
"periwinkle" = "페리윙클블루"
"pine green" = "소나무녹색"
"pink" = "분홍색"
"plum" = "자두색"
"puce" = "짙은보라갈색"
"pumpkin" = "호박색"
"purple" = "보라색"
"raspberry pink" = "라즈베리 핑크"
"raw umber" = "로우 엄버"
"red" = "빨간색"
"red-purple" = "붉은 보라색"
"river blue" = "강가 파랑"
"rose" = "장미색"
"russet" = "적갈색"
"rust" = "녹슨색"
"saffron" = "사프란색"
"sapphire" = "사파이어 블루"
"scarlet" = "선홍색"
"sea foam" = "바다거품 녹색"
"sea green" = "바다 녹색"
"sepia" = "세피아색"
"silver" = "은색"
"sky blue" = "하늘색"
"slate gray" = "슬레이트 회색"
"spring green" = "봄 녹색"
"tan" = "황갈색"
"taupe" = "갈색"
"taupe gray" = "회갈색"
"dark taupe" = "짙은 회갈색"
"taupe medium" = "중간 회갈색"
"pale taupe" = "옅은 갈색"
"purple taupe" = "보라빛 갈색"
"rose taupe" = "장미빛 갈색"
"sandy taupe" = "모래빛 갈색"
"teal" = "청록색"
"turquoise" = "터키석색"
"ultramarine" = "군청색"
"vermilion" = "주홍색"
"vibrant green" = "선명한 초록색"
"violet" = "바이올렛색"
"white" = "흰색"
"woodland green" = "숲 녹색"
"yellow" = "노란색"
"yellow-green" = "연두색"
"zesty green" = "상큼한 레몬 그린"
