[[rulesets]]
[rulesets.rules]
"{construction_menu}" = "{construction_menu}"
"{creatures}" = "{creatures}"
"{items}" = "{items}"
"{materials}" = "{materials}"
"{plants}" = "{plants}"
"{positions}" = "{positions}"
"{skills}" = "{skills}"
"{tasks}" = "{tasks}"
"{tiles}" = "{tiles}"
"{day}" = "{day}"
"{color}" = "{color}"
"{menu}" = "{menu}"
"{workshop}" = "{workshop}"
"{require}" = "{require}"
"{thought}" = "{thought}"
"{memory}" = "{memory}"
"{health}" = "{health}"