base = "memory"

[[rulesets]]
[rulesets.rules]
"{main}" = "{main}"

[[rulesets]]
name = "main"
[rulesets.rules]
"{mind}{memorycolor}dwelling upon{textcolor} {things}{tail}" = "{mind}地{memorycolor}沉思{textcolor}一段{things}的经历。"
"{mind}{memorycolor}remembering{textcolor} {things}{tail}" = "{mind}地{memorycolor}回忆起{textcolor}{things}的经历。"
"{mind}{memorycolor}reliving{textcolor} {things}{tail}" = "{mind}地{memorycolor}重温{textcolor}{things}的经历。"
"{mind::color}{season} {%number}" = "{mind::color}{%number}年 {season}"

[[rulesets]]
name = "wired"
[rulesets.rules]
"{textcolor}{sex}{kind}{mind}{textcolor1} {wired::things}" = "{textcolor}{sex}{kind}{mind}{textcolor1}当{wired::things}"
"{textcolor}{sex}{kind}{mind}[C:5:0:0] dwelling upon{textcolor1} {wired::things}" = "{textcolor}{sex}{kind}{mind}{textcolor1}{wired::things}"
"{textcolor}{sex}{kind}{mind}[C:5:0:0] remembering{textcolor1} {wired::things}" = "{textcolor}{sex}{kind}{mind}{textcolor1}{wired::things}"
"{textcolor}body." = "{textcolor}body."
"{textcolor}dead body." = "{textcolor}dead body."
"{textcolor}goblet, cup or mug." = ""
"{textcolor}{building_name}{tail}" = "{textcolor}{building_name}"
"{textcolor}{memory::realiton}{tail}" = "{textcolor}和{memory::realiton}"

[[rulesets]]
name = "wired::things"
[rulesets.rules]
"seeing {memory::num}{building_own}{building_quility}{building_put}" = "当看到{building_own}{building_quility}{building_put}"
"near {memory::num}{building_own}{building_quility}{building_put}" = "当靠近{building_own}{building_quility}{building_put}"
"playing with a" = "在玩了一个"
"talking with {memory::num}" = "进行交谈"

[[rulesets]]
name = "things"
[rulesets.rules]
"sleeping in a bedroom like a personal palace." = "在一间个人宫殿般的卧室里入睡"
"sleeping in a {memory::poorroom} bedroom" = "在一间{memory::poorroom}卧室入睡"
"dining in a {memory::poorroom} dining room." = "在一间{memory::poorroom}餐厅就餐"
"dining in a {memory::poorroom} dining" = "在一间{memory::poorroom}餐厅就餐"
"dining in a {memory::poorroom}" = "在一间{memory::poorroom}餐厅就餐"
"sleeping uneasily due to noise." = "因噪音而睡不安稳"
"being disturbed during sleep by loud noises." = "在睡眠中被巨大的噪音干扰"
"loud noises made it impossible to sleep." = "在嘈杂的声音使其无法入睡"
"sleeping without a proper room." = "在没有适当房间的情况下入睡"
"sleeping in the {memory::poorroom}." = "处于{memory::poorroom}睡觉"
"sleeping on the {memory::poorroom}." = "在{memory::poorroom}之上睡觉"
"when {memory::poorroom}." = "在{memory::poorroom}时"
"having a {memory::poorroom} drink." = "享用了一杯{memory::poorroom}饮品"
"eating a {memory::poorroom}." = "享用了一顿{memory::poorroom}"
"being forced to eat vermin to survive." = "被迫捕食害虫以求生后."
"drinking nasty water." = "饮用难喝的水."
"drinking the same old booze." = "反复饮用同一种酒."
"eating the same old food." = "反复食用同一种食物."
"having a drink without using a goblet, cup or mug." = "未使用杯子饮酒"
"having a drink without using a" = "未使用杯子饮酒"
"being forced to eat a beloved creature to survive." = "被迫食用心爱的生物以求生"
"being forced to eat a treasured pet to survive." = "被迫食用珍贵的宠物以求生"
"seeing {memory::num}{building_own}{building_quility}{building_put} {building_name}" = "看到{building_own}{building_quility}{building_put}{building_name}时"
"near {memory::num}{building_own}{building_quility}{building_put} {building_name}" = "靠近{building_own}{building_quility}{building_put}{building_name}时"
"being near to a {::creatures::caste::singular} in a cage." = "靠近笼子里的{::creatures::caste::singular}"
"a bath." = "洗完澡"
"a soapy bath." = "洗完肥皂澡"
"being near to a waterfall." = "靠近瀑布"
"retching on a miasma." = "在臭气中干呕"
"choking on smoke/ underground." = "在地下被烟雾呛到"
"choking on dust underground." = "在地下被灰尘呛到"
"at the lack of chairs." = "没有椅子可用"
"eating at a crowded table." = "在拥挤的桌子旁进食"
"at the lack of dining tables." = "没有餐桌可用"
"being pestered by a {::creatures::caste::singular}." = "被{::creatures::caste::singular}骚扰"
"being accosted by a {::creatures::caste::singular}." = "被{::creatures::caste::singular}冒犯"
"being near a {::creatures::caste::singular}." = "靠近{::creatures::caste::singular}"
"talking with the spouse." = "与配偶交谈"
"talking with mother." = "与母亲交谈"
"talking with father." = "与父亲交谈"
"talking with a lover." = "与爱人交谈"
"talking with a friend." = "与朋友交谈"
"talking with a sibling." = "与兄弟姐妹交谈"
"talking with a child." = "与孩子交谈"
"talking with somebody." = "与某人交谈"
"talking with an acquaintance." = "与熟人交谈"
"watching a performance." = "观看表演"
"talking to a pillar of society." = "与社会栋梁交谈"
"interacting with a pet." = "与宠物互动"
"interacting with a animal training partner." = "与动物训练伙伴互动"
"visiting with a animal training partner." = "拜访动物训练伙伴"
"visiting with a pet." = "拜访宠物"
"discussing {memory::num} {memory::realiton}'s problems." = "讨论{memory::realiton}的问题"
"discussing {memory::num} {memory::realiton}'s" = "讨论{memory::realiton}的问题"
"discussing somebody's problems." = "讨论某人的问题"
"when forced to talk to somebody annoying." = "被迫与令人讨厌的人交谈时"
"bringing somebody to rest in bed." = "将某人带到床上休息"
"giving somebody food." = "给某人食物"
"giving somebody water." = "给某人水"
"making a friend." = "交到新朋友"
"getting into an argument." = "发生争吵"
"forming a grudge." = "产生怨恨"
"adopting a new pet." = "收养新宠物"
"at being separated from a loved one." = "与挚爱分离"
"at being separated from loved ones." = "与挚爱们分离"
"at work." = "在工作中"
"producing a masterwork." = "制作杰作"
"upon mastering {::skills::name}." = "精通{::skills::name}"
"creating an artifact." = "制作神器"
"suffering the travesty of art defacement." = "遭受艺术品破坏的悲剧"
"forming a bond with an animal training partner" = "与动物训练伙伴建立联系"
"felling a tree" = "砍倒一棵树"
"putting a piece on display" = "展示一件物品"
"to be wearing old clothing" = "穿着破旧的衣服"
"to be wearing tattered clothing" = "穿着破烂的衣服"
"to have clothes rot off" = "衣服烂掉"
"to be uncovered" = "没有穿裤子"
"to have no shirt" = "没有衬衫"
"to have no shoes" = "没有鞋"
"giving birth to *" = "生下*"
"becoming a parent" = "成为父母"
"gaining a sibling" = "获得兄弟姐妹"
"gaining siblings" = "获得多个兄弟姐妹"
"while getting married" = "结婚时"
"was caught up in a new romance" = "陷入新的恋情"
"a miscarriage" = "流产之"
"spouse's miscarriage" = "配偶的流产之"
"to be elected" = "被选举"
"to be re-elected" = "被连任"
"entering the nobility" = "进入贵族身份"
"receiving a higher rank of nobility" = "获得更高爵位的贵族身份"
"having a {memory::poorroom} tomb after gaining another year" = "获得另一个生日后拥有{memory::poorroom}陵墓"
"about not having a tomb after gaining another year" = "关于获得另一个生日后没有陵墓"
"considering the state of demands" = "考虑需求的状态"
"to have a mandate deadline met" = "满足了强令期限"
"having a mandate deadline missed" = "强令期限错过"
"having a mandate ignored" = "强令被忽视"
"not having enough chests" = "没有足够的箱子"
"not having enough cabinets" = "没有足够的柜子"
"not having enough weapon racks" = "没有足够的武器架"
"not having enough armor stands" = "没有足够的盔甲架"
"by a lesser's pretentious office arrangements" = "因低等贵族的办公室安排而感到不满"
"by a lesser's pretentious sleeping arrangements" = "因低等贵族的睡眠安排而感到不满"
"by a lesser's pretentious dining arrangements" = "因低等贵族的餐饮安排而感到不满"
"by a lesser's pretentious burial arrangements" = "因低等贵族的葬礼安排而感到不满"
"having to conduct an official meeting in a bedroom" = "不得不在卧室进行官方会议"
"having to conduct an official meeting in a dining room" = "不得不在餐厅进行官方会议"
"not having any rooms" = "没有任何房间"
"to have his punishment delayed" = "他的惩罚被推迟"
"to have her punishment delayed" = "她的惩罚被推迟"
"to have his punishment reduced" = "他的惩罚被减轻"
"to have her punishment reduced" = "她的惩罚被减轻"
"punishing somebody with a beating" = "用鞭打惩罚了某人"
"beating somebody with a hammer" = "用锤子鞭打某人"
"being released from confinement" = "从监禁中获释"
"that a criminal could not be properly punished" = "罪犯没有得到适当的惩罚"
"the delayed punishment of a criminal" = "罪犯的惩罚被推迟"
"being confined" = "被监禁"
"considering the scarcity of cages and chains" = "考虑到笼子和链条的稀缺性"
"being beaten" = "被鞭打"
"being beaten with a hammer" = "被锤子鞭打"
"being unable to find a hammer" = "找不到锤子"
"an animal was convicted of a crime" = "动物被判定有罪"
"a long-dead corpse was convicted of a crime" = "一具久远的尸体被判定有罪"
"the bizarre conviction against all reason of the victim of a crime" = "犯罪受害者被不合理地判定有罪"
"upon receiving justice through a criminal's conviction" = "通过罪犯的定罪获得正义"
"when a family member received justice through a criminal's conviction" = "当家庭成员通过罪犯的定罪获得正义时"
"being knocked out during a cave-in" = "在塌方中被击昏"
"being rescued" = "被救援"
"being able to rest and recuperate" = "能够休息和恢复"
"receiving food" = "接受食物"
"receiving water" = "接受水"
"being attacked" = "被攻击"
"being attacked by the dead" = "被死者攻击"
"being haunted by the dead" = "被死者缠住"
"being * by a dead {memory::realiton}" = "被已死的{memory::realiton}*"
"suffering a minor injury" = "遭受轻伤"
"suffering a major injury" = "遭受重伤"
"seeing a {::creatures::caste::singular} die." = "看到{::creatures::caste::singular}死亡"
"seeing a {::creatures::caste::singular}'s dead body." = "看到{::creatures::caste::singular}的尸体"
"seeing a {::creatures::caste::singular}'s dead" = "看到{::creatures::caste::singular}的尸体"
"seeing a {::creatures::caste::singular}'s" = "看到{::creatures::caste::singular}的尸体"
"being tormented in nightmares by a dead {memory::realiton}" = "被已死的{memory::realiton}在噩梦中折磨"
"being forced to endure the decay of a {memory::realiton}" = "被迫忍受{memory::realiton}的腐烂尸体"
"being near to a conflict" = "靠近冲突"
"while in conflict" = "处于冲突中"
"when joining an existing conflict" = "加入已存在的冲突时"
"while killing somebody" = "杀死某个矮人时"
"a sparring session" = "比武练习结束"
"during long patrol duty" = "长时间巡逻期间"
"{memory::crime}" = "{memory::crime}"
"while yelling at somebody in charge" = "对负责人发泄时"
"while crying on somebody in charge" = "对负责人哭诉时"
"being unable to find a priest to yell at" = "找不到可以发泄的牧师"
"being unable to find somebody in charge to yell at" = "找不到可以发泄的负责人"
"being unable to find a priest to cry on" = "找不到可以哭诉的牧师"
"being unable to find somebody in charge to cry on" = "找不到可以哭诉的负责人"
"when caught in {memory::weather}" = "遇到{memory::weather}时"
"at being out in the sunshine again" = "再次沐浴在阳光下"
"being nauseated by the sun" = "被阳光弄得反胃"
"due to inebriation" = "因为醉酒"
"while performing." = "在表演时"
"performing." = "表演时"
"experiencing trauma" = "在经受痛苦经历"
"a satisfying acquisition." = "在拿到满意的东西"
"putting on {memory::num} {memory::quality} item." = "在穿戴上一件{memory::quality}物品"
"putting on {memory::num} {memory::quality}" = "在穿戴上一件{memory::quality}物品"
"playing with a {::items::toy::main}" = "在玩了一个{::items::toy::main}"
"making a friend" = "交到一个朋友"
"teaching {memory::skill}" = "教授{memory::skill}"
"improving {memory::skill}" = "在提高{memory::skill}"
"learning about {memory::skill}" = "学习{memory::skill}"

[[rulesets]]
name = "memory::num"
optional = true
[rulesets.rules]
"the" = "这个"
"a" = "一个"
"an" = "一个"

[[rulesets]]
name = "memory::quality"
[rulesets.rules]
"Well-crafted" = "良好做工"
"Finely-crafted" = "精美做工"
"Superior" = "上等的"
"Exceptional" = "卓越的"
"Masterful" = "大师的"
"Artifact" = "神器"

[[rulesets]]
name = "memory::skill"
[rulesets.rules]
"Mining" = "采矿"
"Woodcutting" = "伐木"
"Carpentry" = "木工"
"Engraving" = "雕刻"
"Masonry" = "石工"
"Animal Training" = "驯兽"
"Animal Caretaking" = "动物护理"
"Fish Dissection" = "剖鱼"
"Animal Dissection" = "动物解剖"
"Fish Cleaning" = "洗鱼"
"Butchery" = "屠宰"
"Trapping" = "诱捕"
"Tanning" = "制革"
"Weaving" = "编织"
"Brewing" = "酿造"
"Tailoring" = "裁缝"
"Milling" = "碾磨"
"Threshing" = "脱粒"
"Cheesemaking" = "制酪"
"Milking" = "挤奶"
"Cooking" = "烹饪"
"Planting" = "种植"
"Herbalism" = "草药学"
"Fishing" = "捕鱼"
"Furnace Operation" = "火炉操作"
"Strand Extraction" = "缕丝提取"
"Weaponsmithing" = "武器锻造"
"Armorsmithing" = "盔甲锻造"
"Blacksmithing" = "锻造"
"Gem Cutting" = "宝石切割"
"Gem Setting" = "宝石镶嵌"
"Woodcrafting" = "木艺"
"Stonecrafting" = "石艺"
"Metalcrafting" = "金属工艺"
"Glassmaking" = "玻璃制作"
"Leatherworking" = "皮革加工"
"Bone Carving" = "骨雕"
"Knife" = "小刀使用"
"Crossbow" = "弩术"
"Shield" = "盾牌使用"
"Armor" = "盔甲使用"
"Siege Engineering" = "攻城器工程"
"Siege Operation" = "攻城器操作"
"Bowyery" = "制弓"
"Lashing" = "鞭术"
"Archery" = "射术"
"Blowgun" = "吹管术"
"Throwing" = "投掷"
"Mechanics" = "机械学"
"machinery" = "机械"
"Druidism" = "德鲁伊教"
"Ambushing" = "伏击"
"Wound Dressing" = "裹伤"
"Diagnosis" = "诊断"
"Surgery" = "外科手术"
"Bone Setting" = "骨科"
"Suturing" = "缝合"
"Crutch-walking" = "拄拐行走"
"Wood Burning" = "烧炭"
"Lye Making" = "制碱液"
"Soap Making" = "制皂"
"Potash Making" = "制草碱"
"Dyeing" = "染色"
"Pump Operation" = "泵机操作"
"Swimming" = "游泳"
"Persuasion" = "说服"
"Negotiation" = "交涉"
"Judging Intent" = "意图判断"
"Appraisal" = "估价"
"Organization" = "组织能力"
"Record Keeping" = "记录"
"Lying" = "说谎"
"Intimidation" = "恐吓"
"Conversation" = "交谈"
"Comedy" = "喜剧表演"
"Flattery" = "奉承"
"Consolation" = "安慰"
"Pacification" = "调解"
"Tracking" = "追踪"
"Studying" = "学习"
"Concentration" = "专注"
"Discipline" = "遵守纪律"
"Observation" = "观察"
"Wordsmithing" = "文字创作"
"Writing" = "写作"
"Poetry" = "作诗"
"Reading" = "阅读"
"Speaking" = "演讲"
"Coordination" = "协调"
"Balance" = "平衡"
"Leadership" = "领导"
"Teaching" = "教学"
"Fighting" = "战斗"
"Wrestling" = "摔跤"
"Biting" = "撕咬"
"Striking" = "搏击"
"Kicking" = "踢击"
"Dodging" = "躲闪"
"Misc. Object" = "杂物使用"
"Knapping" = "碎石"
"Tactics" = "战术"
"Shearing" = "剪毛"
"Spinning" = "纺纱"
"Pottery" = "制陶"
"Glazing" = "上釉"
"Pressing" = "压榨"
"Beekeeping" = "养蜂"
"Wax Working" = "蜡工"
"Climbing" = "攀爬"
"Gelding" = "阉割"
"Dancing" = "舞蹈"
"Musicianship" = "音乐演奏"
"Singing" = "歌唱"
"Keyboard" = "键盘演奏"
"Stringed Instrument" = "弦乐演奏"
"Wind Instrument" = "管乐演奏"
"Percussion" = "打击乐演奏"
"Critical Thinking" = "批判性思维"
"Logic" = "逻辑学"
"Mathematics" = "数学"
"Astronomy" = "天文学"
"Chemistry" = "化学"
"Geography" = "地理学"
"Optics Engineering" = "光学工程"
"Fluid Engineering" = "流体工程"
"Papermaking" = "造纸"
"Bookbinding" = "书籍装订"
"Scheming" = "阴谋策划"
"Riding" = "骑术"
"Stonecutting" = "切石"
"Stone Carving" = "石雕"
"Axe" = "斧术"
"Sword" = "剑术"
"Mace" = "页锤术"
"Hammer" = "战锤术"
"Spear" = "矛术"
"Marksmanship" = "射击术"
"Pike" = "长枪术"
"bow" = "弓术"
"Furnace" = "火炉操作"

[[rulesets]]
name = "building_quility"
[rulesets.rules]
" very fine" = "非常精美的"
" splendid" = "极佳的"
" wonderful" = "奇妙的"
" completely sublime" = "完全卓越的"
" fine" = "非常精美的"

[[rulesets]]
name = "building_put"
optional = true
[rulesets.rules]
" tastefully arranged" = "精心布置的"

[[rulesets]]
name = "building_own"
optional = true
[rulesets.rules]
" own" = "自己的"

[[rulesets]]
name = "building_name"
[rulesets.rules]
"{::items::main}" = "{::items::main}"
"seat" = "座位"
"{::construction_menu}" = "{::construction_menu}"

[[rulesets]]
name = "memory::poorroom"
[rulesets.rules]
"horribly substandard" = "严重不合标准的"
"horrible" = "可怕的"
"awful" = "糟糕的"
"very poor" = "非常差的"
"poor" = "差的"
"legendary" = "传奇的"
"fantastic" = "奇妙的"
"great" = "绝妙的"
"very good" = "非常好的"
"good" = "好的"
"mud" = "淤泥"
"dirt" = "泥土"
"grass" = "草"
"rocks" = "岩石"
"ice" = "冰"
"a rough cave floor" = "粗糙的洞穴楼板"
"floor" = "楼板"
"a pile of driftwood" = "一堆浮木"
"drowsy" = "昏昏欲睡"
"utterly sleep-deprived" = "全然睡眠不足"
"pretty decent" = "相当不错的"
"fine" = "精美的"
"wonderful" = "奇妙的"
"truly decadent" = "真正的奢华的"
"pretty decent meal" = "相当不错的饭菜"
"fine dish" = "精美的菜肴"
"wonderful dish" = "奇妙的菜肴"
"truly decadent dish" = "真正的奢华菜肴"
"legendary meal" = "传奇的饭菜"
"thirsty" = "口渴"
"hungry" = "饥饿"
"dehydrated" = "脱水"
"starving" = "饿死"

[[rulesets]]
name = "memory::realiton"
[rulesets.rules]
"animal training partner." = "动物训练伙伴"
"pet." = "宠物"
"spouse" = "配偶"
"mother" = "母亲"
"father" = "父亲"
"lover" = "爱人"
"friend" = "朋友"
"acquaintance" = "熟人"
"sibling" = "兄弟姐妹"
"child" = "孩子"
"somebody" = "某人"
"somebody annoying" = "令人讨厌的人"
"still annoying acquaintance" = "仍令人讨厌的熟人"
"and still annoying acquaintance" = "且仍令人讨厌的熟人"

[[rulesets]]
name = "memory::crime"
[rulesets.rules]
"throwing something" = "扔东西"
"toppling something over" = "推倒东西"
"smashing up a building" = "破坏建筑"
"starting a fist fight" = "开始打架"

[[rulesets]]
name = "memory::weather"
[rulesets.rules]
"the rain" = "下雨"
"a snow storm" = "下雪"
"freakish weather" = "异常天气"

[[rulesets]]
name = "dead"
[rulesets.rules]
"human's dead body." = "人类尸体"
"goblin's dead body." = "哥布林尸体"
"human's dead" = "人类尸体"
"goblin's dead" = "哥布林尸体"

[[rulesets]]
name = "sex"
[rulesets.rules]
"He" = "他"
"She" = "她"

[[rulesets]]
name = "mind"
[rulesets.rules]
"{mind::color}{mind::text}" = "{mind::color}{mind::text}"

[[rulesets]]
name = "mind::color"
optional = true
[rulesets.rules]
"[C:2:0:1]" = "[C:2:0:1]"
"[C:2:0:0]" = "[C:2:0:0]"
"[C:4:0:1]" = "[C:4:0:1]"
"[C:4:0:0]" = "[C:4:0:0]"
"[C:7:0:1]" = "[C:7:0:1]"
"[C:7:0:0]" = "[C:7:0:0]"
"[C:3:0:1]" = "[C:3:0:1]"
"[C:3:0:0]" = "[C:3:0:0]"
"[C:1:0:1]" = "[C:1:0:1]"
"[C:6:0:1]" = "[C:6:0:1]"
"[C:6:0:0]" = "[C:6:0:0]"
"[C:5:0:1]" = "[C:5:0:1]"
"[C:5:0:0]" = "[C:5:0:0]"

[[rulesets]]
name = "mind::text"
[rulesets.rules]
"Adoration" = "崇拜"
"Admiration" = "钦佩"
"Affection" = "喜爱"
"Aroused" = "兴奋"
"Caring" = "关心"
"Empathy" = "同理"
"Enraptured" = "陶醉"
"Fondness" = "喜欢"
"Gratitude" = "感激"
"Lustful" = "难以自持"
"Love" = "爱意"
"Passionate" = "热情"
"Pleasure" = "愉悦"
"Proud" = "自豪"
"Repentant" = "忏悔"
"Sympathy" = "同情"
"Tenderness" = "温柔"
"Amused" = "好笑"
"Blissful" = "极度幸福"
"Content" = "满足"
"Delighted" = "欣喜"
"Elated" = "兴高采烈"
"Enjoyment" = "愉快"
"Euphoric" = "欣快"
"Expectant" = "期待"
"Free" = "自由"
"Gaiety" = "欢快"
"Happy" = "开心"
"Hope" = "有希望"
"Jovial" = "开朗"
"Joy" = "喜悦"
"Relieved" = "放心"
"Satisfied" = "满意"
"Triumph" = "得意"
"Optimistic" = "乐观"
"Astonished" = "惊讶"
"Awe" = "敬畏"
"Excited" = "兴奋"
"Eager" = "渴望"
"Exhilarated" = "振奋"
"Interested" = "有趣"
"Wonder" = "惊叹"
"Accepting" = "接纳"
"Ambivalent" = "矛盾"
"Grim Satisfaction" = "冷酷的满足"
"Suspicious" = "怀疑"
"Aggravated" = "恼火"
"Agitated" = "焦躁"
"Annoyed" = "烦恼"
"Anxious" = "焦虑"
"Bitter" = "苦涩"
"Bored" = "无聊"
"Confused" = "困惑"
"Contemptuous" = "轻蔑"
"Dejected" = "沮丧"
"Disappointed" = "失望"
"Disillusioned" = "幻灭"
"Dislike" = "不喜欢"
"Embarrassed" = "尴尬"
"Exasperated" = "恼怒"
"Frustrated" = "挫败"
"Gloomy" = "阴郁"
"Glum" = "郁闷"
"Grouchy" = "脾气暴躁"
"Guilty" = "内疚"
"Indignant" = "愤慨"
"Insulted" = "受辱"
"Irritated" = "恼火"
"Isolated" = "被孤立"
"Lonely" = "孤独"
"Regretful" = "后悔"
"Resentful" = "怨恨"
"Restless" = "坐立不安"
"Self-Pity" = "自怜"
"Uneasy" = "不安"
"Worried" = "担心"
"Anguish" = "痛苦万分"
"Ashamed" = "羞愧"
"Despair" = "绝望"
"Disgusted" = "厌恶"
"Distressed" = "痛苦"
"Empty" = "空虚"
"Existential Crisis" = "陷入存在危机"
"Frightened" = "惊恐"
"Grieved" = "悲痛"
"Hopeless" = "毫无希望"
"Humiliated" = "屈辱"
"Mortified" = "羞愧难当"
"Panicked" = "惊慌失措"
"Sad" = "悲伤"
"Shaken" = "震惊不已"
"Shocked" = "震惊"
"Alarmed" = "惊慌"
"Afraid" = "害怕"
"Angry" = "愤怒"
"Ferocity" = "凶狠"
"Horrified" = "惊骇"
"Loathing" = "憎恶"
"Outraged" = "暴怒不已"
"Terrified" = "极度恐惧"
"Vengeful" = "复仇心切"

[[rulesets]]
name = "kind"
[rulesets.rules]
" is" = "感到"
" was" = "感到"
" didn't feel" = ""
" doesn't feel" = ""
" feels" = "感到"
" felt" = "感到"

[[rulesets]]
name = "textcolor"
[rulesets.rules]
"[C:7:0:1]" = "[C:7:0:1]"
"[C:7:0:0]" = "[C:7:0:0]"

[[rulesets]]
name = "textcolor1"
optional = true
[rulesets.rules]
"[C:7:0:1]" = "[C:7:0:1]"
"[C:7:0:0]" = "[C:7:0:0]"

[[rulesets]]
name = "memorycolor"
[rulesets.rules]
"[C:5:0:1] " = "[C:5:0:1]"
"[C:5:0:0] " = "[C:5:0:0]"

[[rulesets]]
name = "tail"
optional = true
[rulesets.rules]
"." = "."

[[rulesets]]
name = "season"
[rulesets.rules]
"spring" = "春"
"summer" = "夏"
"autumn" = "秋"
"winter" = "冬"