base = "professions"

[[rulesets]]
[rulesets.rules]
"Woodworker" = "나무꾼"
"Stoneworker" = "석공"
"Ranger" = "레인저"
"Hunter" = "사냥꾼"
"Metalsmith" = "금속 대장장이"
"Armorer" = "갑옷장이"
"Metalcrafter" = "금속 세공인"
"Jeweler" = "보석 세공인"
"Craftsman" = "장인"
"Stonecrafter" = "석공예가"
"Fishery Worker" = "어업 노동자"
"Farmer" = "농부"
"Soap Maker" = "비누 제조자"
"Engineer" = "기술자"
"Clerk" = "서기"
"Administrator" = "관리자"
"Trader" = "무역상"
"Doctor" = "의사"
"Merchant" = "상인"
"Hammer Lord" = "전쟁망치의 군주"
"Spearmaster" = "창술의 달인"
"Elite Crossbowman" = "정예 석궁수"
"Elite Wrestler" = "정예 레슬러"
"Axe Lord" = "전투도끼의 군주"
"Swordmaster" = "검술의 달인"
"Mace Lord" = "철퇴의 군주"
"Pikemaster" = "장창술의 달인"
"Elite Bowman" = "정예 궁수"
"Master Blowgunner" = "블로우건의 달인"
"Master Lasher" = "채찍의 달인"
"Recruit" = "신병"
"Hunting" = "사냥"
"War" = "전쟁"
"Master Thief" = "도둑의 달인"
"Thief" = "도둑"
"Peasant" = "평민"
"Child" = "아이"
"Baby" = "아기"
"Drunk" = "주정뱅이"
"Monster Slayer" = "괴물 사냥꾼"
"Scout" = "정찰병"
"Beast Hunter" = "맹수 사냥꾼"
"Snatcher" = "유괴범"
"Mercenary" = "용병"
"Performer" = "공연자"
"Bard" = "음유시인"
"Sage" = "현자"
"Scholar" = "학자"
"Philosopher" = "철학자"
"Historian" = "역사학자"
"Naturalist" = "박물학자"
"Scribe" = "필경사"
"Tavern Keeper" = "주점지기"
"Criminal" = "범죄자"
"Peddler" = "행상인"
"Prophet" = "예언자"
"Pilgrim" = "순례자"
"Monk" = "수도승"
"Messenger" = "전령"
"craftsdwarf" = "드워프 공예가"
"Elite Marksdwarf" = "정예 드워프 석궁수"
"Elite Bowdwarf" = "정예 드워프 궁수"
"{::skills::name}" = "{::skills::name}"
