base = "skills"

[[rulesets]]
[rulesets.rules]
"{level} {name}" = "{level}{name}"

[[rulesets]]
name = "level"
[rulesets.rules]
"Dabbling" = "어설픈"
"Novice" = "초보"
"Adequate" = "그럭저럭한"
"Competent" = "자격있는"
"Skilled" = "숙련된"
"Proficient" = "능숙한"
"Talented" = "재능있는"
"Adept" = "특기인"
"Expert" = "전문적인"
"Professional" = "프로급"
"Accomplished" = "노련한"
"Great" = "위대한"
"Master" = "대가급"
"High Master" = "고수급"
"Grand Master" = "거장급"
"Legendary" = "전설적인"

[[rulesets]]
name = "name"
[rulesets.rules]
"Miner" = "광부"
"Woodcutter" = "벌목꾼"
"Carpenter" = "목수"
"Engraver" = "조각사"
"Mason" = "석공"
"Animal Trainer" = "동물조련사"
"Animal Caretaker" = "동물관리인"
"Fish Dissector" = "물고기해부사"
"Animal Dissector" = "동물해부사"
"Fish Cleaner" = "물고기손질공"
"Butcher" = "도살꾼"
"Trapper" = "덫꾼"
"Tanner" = "무두질공"
"Weaver" = "직조공"
"Brewer" = "양조사"
"Clothier" = "재단사"
"Miller" = "제분공"
"Thresher" = "탈곡공"
"Cheesemaker" = "치즈제조공"
"Milker" = "착유공"
"Cook" = "요리사"
"Planter" = "파종자"
"Herbalist" = "약초채집가"
"Fisherman" = "어부"
"Furnace Operator" = "용광로조작자"
"Strand Extractor" = "실추출자"
"Weaponsmith" = "무기대장장이"
"Armorsmith" = "갑옷대장장이"
"Blacksmith" = "대장장이"
"Gem Cutter" = "보석연마사"
"Gem Setter" = "보석세팅사"
"Woodcrafter" = "목공예가"
"Stone Crafter" = "석공예가"
"Metal Crafter" = "금속 세공인"
"Glassmaker" = "유리 세공인"
"Leatherworker" = "가죽 세공인"
"Bone Carver" = "뼈 조각가"
"Axeman" = "도끼병"
"Swordsman" = "검객"
"Knife User" = "단검 사용자"
"Maceman" = "철퇴병"
"Hammerman" = "전쟁망치병"
"Spearman" = "창병"
"Crossbowman" = "석궁병"
"Shield User" = "방패 사용자"
"Armor User" = "갑옷 사용자"
"Siege Engineer" = "공성무기 기술자"
"Siege Operator" = "공성무기 조작자"
"Bowyer" = "활 제작자"
"Pikeman" = "장창병"
"Lasher" = "채찍병"
"Bowman" = "궁수"
"Blowgunner" = "취관수"
"Thrower" = "투척병"
"Mechanic" = "기계공"
"Druid" = "드루이드"
"Ambusher" = "매복자"
"Wound Dresser" = "상처 붕대사"
"Diagnostician" = "진단 의사"
"Surgeon" = "외과 의사"
"Bone Doctor" = "정형외과 의사"
"Suturer" = "봉합사"
"Crutch-walker" = "목발 보행자"
"Wood Burner" = "목탄 제조자"
"Lye Maker" = "잿물 제조자"
"Soaper" = "비누 제조자"
"Potash Maker" = "포타시 제조자"
"Dyer" = "염색공"
"Pump Operator" = "펌프 조작자"
"Swimmer" = "수영자"
"Persuader" = "설득자"
"Negotiator" = "협상가"
"Judge of Intent" = "의도 판단"
"Appraiser" = "감정가"
"Organizer" = "조직가"
"Record Keeper" = "기록 관리인"
"Liar" = "거짓말쟁이"
"Intimidator" = "위협가"
"Conversationalist" = "대화가"
"Comedian" = "희극인"
"Flatterer" = "아첨가"
"Consoler" = "위로자"
"Pacifier" = "중재자"
"Tracker" = "추적자"
"Student" = "학생"
"Concentration" = "집중"
"Discipline" = "규율 준수"
"Observer" = "관찰자"
"Wordsmith" = "문학가"
"Writer" = "작가"
"Poet" = "시인"
"Reader" = "독자"
"Speaker" = "화자"
"Coordination" = "협응"
"Balance" = "균형"
"Leader" = "지도자"
"Teacher" = "교사"
"Fighter" = "전사"
"Archer" = "궁수"
"Wrestler" = "레슬러"
"Biter" = "물어뜯는 자"
"Striker" = "타격자"
"Kicker" = "발차기꾼"
"Dodger" = "회피자"
"Misc. Object User" = "잡동사니 사용자"
"Knapper" = "석기 제작자"
"Tactician" = "전술가"
"Shearer" = "털깎이"
"Spinner" = "방적공"
"Potter" = "도예가"
"Glazer" = "유약공"
"Presser" = "압착공"
"Beekeeper" = "양봉가"
"Wax Worker" = "밀랍공"
"Climber" = "등반가"
"Gelder" = "거세사"
"Dancer" = "무용가"
"Musician" = "음악가"
"Singer" = "가수"
"Keyboardist" = "건반 연주자"
"Stringed Instrumentalist" = "현악 연주자"
"Wind Instrumentalist" = "관악 연주자"
"Percussionist" = "타악 연주자"
"Critical Thinker" = "비판적 사고가"
"Logician" = "논리학자"
"Mathematician" = "수학자"
"Astronomer" = "천문학자"
"Chemist" = "화학자"
"Geographer" = "지리학자"
"Optics Engineer" = "광학 공학자"
"Fluid Engineer" = "유체 공학자"
"Papermaker" = "제지공"
"Bookbinder" = "제본사"
"Schemer" = "모략가"
"Rider" = "기수"
"Stonecutter" = "석재 절단공"
"Stone Carver" = "석조각가"
"fisherdwarf" = "드워프 어부"
"axedwarf" = "드워프 도끼병"
"swordsdwarf" = "드워프 검병"
"macedwarf" = "드워프 철퇴병"
"hammerdwarf" = "드워프 전쟁망치병"
"speardwarf" = "드워프 창병"
"marksdwarf" = "드워프 석궁병"
"pikedwarf" = "드워프 장창병"
"bowdwarf" = "드워프 궁수"
