base = "workshop"

[[rulesets]]
[rulesets.rules]
"{name}" = "{name}"

[[rulesets]]
name = "name"
[rulesets.rules]
"Metalsmith's Forge" = "금속 대장간"
"stoneworker's Workshop" = "석공 작업장"
"bowyer's workshop" = "활장이 작업장"
"siege workshop" = "공성무기 작업장"
"Clothier's shop" = "재단사 작업장"
"Dyer's shop" = "염색소"
"Butcher's shop" = "도축장"
"Tanner's shop" = "무두질 작업장"
"Jeweler's workshop" = "보석 세공 작업장"
"Craftsdwarf's Workshop" = "수공예 작업장"
"Carpenter's Workshop" = "목수 작업장"
