base = "menu"

[[rulesets]]
[rulesets.rules]
"{main}{&0}" = "{main}{&0}"

[[rulesets]]
name = "&0"
optional = true
[rulesets.rules]
" (opens menu)" = " (메뉴 열기)"
" (use bars)" = " (주괴 사용)"
" (use ore)" = " (광석 사용)"

[[rulesets]]
name = "main"
[rulesets.rules]
"{dyer}" = "{dyer}"
"{make}" = "{make}"
"{smelt}" = "{smelt}"
"{kiln}" = "{kiln}"