base = "menu::kiln"

[[rulesets]]
[rulesets.rules]
"Glaze clay/stone craft" = "점토/석재 공예품에 유약 바르기"
"Glaze clay/stone jug" = "점토/석재 주전자에 유약 바르기"
"Glaze clay/stone statue" = "점토/석재 조각상에 유약 바르기"
"Glaze large clay/stone pot" = "점토/석재 큰 항아리에 유약 바르기"
"Make large clay pot" = "큰 점토 항아리 만들기"
"Make plaster powder" = "석고 가루 만들기"
"Make large wooden gem" = "대형 목제 보석 만들기"
"Sew leather image" = "가죽 문양 꿰매기"
"Sew cloth image" = "천 문양 꿰매기"
"Sew silk image" = "비단 문양 꿰매기"
"Sew yarn image" = "실 문양 꿰매기"
"Stud with" = "박기"
"Brew drink from fruit" = "과일로 술 빚기"
"Brew drink from plant" = "식물로 술 빚기"
"Make soap from oil" = "식물성 기름으로 비누 만들기"
"Make soap from tallow" = "우지로 비누 만들기"
"Make quire" = "종이 묶음 만들기"
"Make scroll" = "두루마리 만들기"
"Make wax crafts" = "밀랍 공예품 만들기"
"Bind book" = "책 제본하기"
"Decorate with horn" = "뿔로 장식하기"
"Decorate with ivory/tooth" = "상아/이빨로 장식하기"
"Decorate with pearl" = "진주로 장식하기"
"Make sheet from plant" = "식물로 종이 장 만들기"
"Milk animal" = "동물 젖 짜기"
"Process plant to bag" = "자루로 씨앗 털기"
"Shear animal" = "동물 털 깎기"
"Tan a hide" = "가죽 한 장 무두질하기"
"Press honey from honeycomb" = "벌집에서 꿀 짜내기"
"Press liquid from fruit" = "과일에서 액체 짜내기"
"Press liquid from paste" = "페이스트에서 액체 짜내기"
"Press plant slurry into paper sheet" = "식물 펄프를 압착해 종이 장 만들기"
"Slaughter {::creatures::caste::singular}" = "도축 {::creatures::caste::singular}"
"Slaughter {::creatures::name::singular}" = "도축 {::creatures::name::singular}"
"Resting orientation" = "대기 방향"
"Bolts loaded" = "장전된 볼트 수"
"Bolts nearby and available: " = "근처에서 사용 가능한 볼트 수: "
"Bolts nearby but assigned to squads: " = "근처에 있지만 부대에 할당된 볼트 수: "
"Bolts nearby but assigned to hunters: " = "근처에 있지만 사냥꾼에게 할당된 볼트 수: "
"Keep loaded but do not stand ready" = "장전은 유지하지만 조작자는 배치하지 않기"
"Stand ready but do not fire" = "조작자는 배치하지만 발사하지 않기"
"Practice fire (uses many bolts!)" = "훈련 사격 실시(볼트를 매우 많이 소모합니다!)"
"Practice fire" = "훈련 사격 실시"
"* Will also target enemies" = "* 적에게도 사격합니다"
"* Place archery targets for better training" = "* 더 나은 훈련을 위해 궁술 과녁을 배치하세요"
"Fire at enemies" = "적에게 사격하기"
"Not in use" = "사용하지 않음"