base = "menu::make"

[[rulesets]]
[rulesets.rules]
"{kind}{^0}{main}" = "{kind}{^0}{main}"

[[rulesets]]
name = "kind"
[rulesets.rules]
"Make" = "제작"
"Forge" = "단조"
"Smelt" = "제련"
"Assemble" = "조립"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
" {::materials::state}" = "{::materials::state}"
" wooden" = "목제"

[[rulesets]]
name = "main"
[rulesets.rules]
" {::items::main}" = "{::items::main}"
" crafts" = "공예품"
" ore" = "광석"
" ash" = "재"