base = "health"

[[rulesets]]
[rulesets.rules]
"[C:7:0:1]{bodypart}, {tissue}" = "[C:7:0:1]{bodypart},{tissue}"

[[rulesets]]
name = "tissue"
[rulesets.rules]
"skin" = "皮肤"
"muscle" = "肌肉"
"fat" = "脂肪"
"nervous tissue" = "神经组织"
"bone" = "骨骼"
"upper spine" = "上背部脊柱"
"middle spine" = "背部脊柱"
"lower spine" = "腰椎"
"skull" = "颅骨"

[[rulesets]]
name = "bodypart"
[rulesets.rules]
"right upper leg" = "右大腿"
"right hand" = "右手"
"left hand" = "左手"
"left lower arm" = "左前臂"
"left upper arm" = "左上臂"
"right upper arm" = "右上臂"
"right lower arm" = "右前臂"
"head" = "头部"
"neck" = "脖子"
"lower body" = "下半身"
"upper body" = "上半身"
"left upper leg" = "左大腿"
"right lower leg" = "右小腿"
"left lower leg" = "左小腿"
"right foot" = "右脚"
"left foot" = "左脚"
"right eye" = "右眼"
"left eye" = "左眼"
"right ear" = "右耳"
"left ear" = "左耳"
"nose" = "鼻子"
"throat" = "喉咙"
"thumb" = "拇指"
"first finger" = "食指"
"second finger" = "中指"
"third finger" = "无名指"
"fourth finger" = "小指"
"first toe" = "大脚趾"
"second toe" = "第二脚趾"
"third toe" = "第三脚趾"
"fourth toe" = "第四脚趾"
"fifth toe" = "第五脚趾"
"mouth" = "嘴巴"
"tongue" = "舌头"
"left cheek" = "左脸颊"
"right cheek" = "右脸颊"
"left eyelid" = "左眼睑"
"right eyelid" = "右眼睑"
"lower lip" = "下唇"
"upper lip" = "上唇"
"upper front teeth" = "上门牙"
"lower front teeth" = "下门牙"
"lower right back teeth" = "右下臼齿"
"upper right back teeth" = "右上臼齿"
"lower left back teeth" = "左下臼齿"
"upper left back teeth" = "左上臼齿"
