base = "items::ammo"

[[rulesets]]
[rulesets.rules]
"{default}" = "{default}"
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "default"
[rulesets.rules]
"{default::^0}{default::main}" = "{default::^0}{default::main}"

[[rulesets]]
name = "default::^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "default::main"
[rulesets.rules]
"ammunition" = "탄약"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{^material}{singular::main}" = "{^material}{singular::main}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{^material}{plural::main}" = "{^material}{plural::main}"

[[rulesets]]
name = "^material"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "singular::main"
[rulesets.rules]
"bolt" = "석궁 볼트"
"arrow" = "화살"
"blowdart" = "블로우다트"

[[rulesets]]
name = "plural::main"
[rulesets.rules]
"bolts" = "석궁 볼트"
"arrows" = "화살"
"blowdarts" = "블로우다트"
