base = "items::boulder"

[[rulesets]]
[rulesets.rules]
"stones" = "돌"
"{::materials}" = "{::materials}"
"gold nuggets" = "금덩이"
"silver nuggets" = "은덩이"
"copper nuggets" = "구리덩이"
"platinum nuggets" = "백금덩이"
