base = "items::branch"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials} " = "{::materials}"

[[rulesets]]
name = "main"
[rulesets.rules]
"branch" = "나뭇가지"
"branches" = "나뭇가지"
