base = "items::cage"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"cage" = "우리"
"cages" = "우리"
"terrarium" = "테라리움"
"terrariums" = "테라리움"
