base = "items::coffin"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"coffin" = "영구"
"coffins" = "영구"
"casket" = "관"
"caskets" = "관"
"sarcophagus" = "석관"
"sarcophagi" = "석관"
