base = "items::fish"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"rotten " = "썩은"

[[rulesets]]
name = "main"
[rulesets.rules]
"fish" = "물고기"
"{::creatures::caste::singular}" = "{::creatures::caste::singular}"
"{::creatures::caste::singular}, ♀" = "{::creatures::caste::singular}, ♀"
"{::creatures::caste::singular}, ♂" = "{::creatures::caste::singular}, ♂"
