base = "items::gem"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"large " = "대형 "
"perfect " = "완벽한 "

[[rulesets]]
name = "main"
[rulesets.rules]
"gem" = "보석"
"gems" = "보석"
"{::gems}" = "{::gems}"
"{::gems::details}" = "{::gems::details}"
