base = "items::gloves"

[[rulesets]]
[rulesets.rules]
"{::items::prefix::maybe_equipment_size}{main}" = "{::items::prefix::maybe_equipment_size}{main}"

[[rulesets]]
name = "main"
[rulesets.rules]
"{default}" = "{default}"
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "default"
[rulesets.rules]
"{default::^0}{default::main}" = "{default::^0}{default::main}"

[[rulesets]]
name = "default::^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "default::main"
[rulesets.rules]
"handwear" = "장갑"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{^material}{^handedness}{^chain}{singular::main}" = "{^material}{^handedness}{^chain}{singular::main}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{^material}{^handedness}{^chain}{plural::main}" = "{^material}{^handedness}{^chain}{plural::main}"

[[rulesets]]
name = "^material"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "^handedness"
optional = true
[rulesets.rules]
"left " = "왼손"
"right " = "오른손"

[[rulesets]]
name = "^chain"
optional = true
[rulesets.rules]
"chain " = "사슬"

[[rulesets]]
name = "singular::main"
[rulesets.rules]
"gauntlet" = "건틀릿"
"glove" = "장갑"
"mitten" = "벙어리장갑"

[[rulesets]]
name = "plural::main"
[rulesets.rules]
"gauntlets" = "건틀릿"
"gloves" = "장갑"
"mittens" = "벙어리장갑"
