base = "items"

[[rulesets]]
[rulesets.rules]
"{^0}{%item_designation:with_number}" = "{^0}{%item_designation:with_number}"

[[rulesets]]
name = "with_number"
[rulesets.rules]
"{main}{$number}" = "{main}{$number}"

[[rulesets]]
name = "$number"
optional = true
[rulesets.rules]
" x{%number}" = " x{%number}"
" (%{%number})" = " (%{%number})"
" [{%number}]" = " [{%number}]"
" <#{%number}>" = " <#{%number}>"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"grown " = "재배한 "

[[rulesets]]
name = "main"
[rulesets.rules]
"{altar}" = "{altar}"
"{bar}" = "{bar}"
"{smallgem}" = "{smallgem}"
"{blocks}" = "{blocks}"
"{rough}" = "{rough}"
"{boulder}" = "{boulder}"
"{wood}" = "{wood}"
"{door}" = "{door}"
"{floodgate}" = "{floodgate}"
"{bed}" = "{bed}"
"{chair}" = "{chair}"
"{chain}" = "{chain}"
"{flask}" = "{flask}"
"{goblet}" = "{goblet}"
"{instrument}" = "{instrument}"
"{toy}" = "{toy}"
"{window}" = "{window}"
"{cage}" = "{cage}"
"{barrel}" = "{barrel}"
"{bucket}" = "{bucket}"
"{animaltrap}" = "{animaltrap}"
"{table}" = "{table}"
"{coffin}" = "{coffin}"
"{statue}" = "{statue}"
"{corpse}" = "{corpse}"
"{weapon}" = "{weapon}"
"{armor}" = "{armor}"
"{shoes}" = "{shoes}"
"{shield}" = "{shield}"
"{helm}" = "{helm}"
"{gloves}" = "{gloves}"
"{box}" = "{box}"
"{bag}" = "{bag}"
"{bin}" = "{bin}"
"{armorstand}" = "{armorstand}"
"{weaponrack}" = "{weaponrack}"
"{cabinet}" = "{cabinet}"
"{figurine}" = "{figurine}"
"{amulet}" = "{amulet}"
"{scepter}" = "{scepter}"
"{ammo}" = "{ammo}"
"{crown}" = "{crown}"
"{ring}" = "{ring}"
"{earring}" = "{earring}"
"{bracelet}" = "{bracelet}"
"{gem}" = "{gem}"
"{anvil}" = "{anvil}"
"{corpsepiece}" = "{corpsepiece}"
"{remains}" = "{remains}"
"{meat}" = "{meat}"
"{fish}" = "{fish}"
"{fish_raw}" = "{fish_raw}"
"{vermin}" = "{vermin}"
"{pet}" = "{pet}"
"{seeds}" = "{seeds}"
"{plant}" = "{plant}"
"{skin_tanned}" = "{skin_tanned}"
"{plant_growth}" = "{plant_growth}"
"{thread}" = "{thread}"
"{cloth}" = "{cloth}"
"{totem}" = "{totem}"
"{pants}" = "{pants}"
"{backpack}" = "{backpack}"
"{quiver}" = "{quiver}"
"{catapultparts}" = "{catapultparts}"
"{ballistaparts}" = "{ballistaparts}"
"{siegeammo}" = "{siegeammo}"
"{ballistaarrowhead}" = "{ballistaarrowhead}"
"{trapparts}" = "{trapparts}"
"{trapcomp}" = "{trapcomp}"
"{drink}" = "{drink}"
"{dye}" = "{dye}"
"{powder_misc}" = "{powder_misc}"
"{cheese}" = "{cheese}"
"{food}" = "{food}"
"{liquid_misc}" = "{liquid_misc}"
"{coin}" = "{coin}"
"{glob}" = "{glob}"
"{rock}" = "{rock}"
"{pipe_section}" = "{pipe_section}"
"{hatch_cover}" = "{hatch_cover}"
"{grate}" = "{grate}"
"{quern}" = "{quern}"
"{millstone}" = "{millstone}"
"{splint}" = "{splint}"
"{crutch}" = "{crutch}"
"{traction_bench}" = "{traction_bench}"
"{orthopedic_cast}" = "{orthopedic_cast}"
"{tool}" = "{tool}"
"{slab}" = "{slab}"
"{egg}" = "{egg}"
"{book}" = "{book}"
"{sheet}" = "{sheet}"
"{branch}" = "{branch}"
"{bookcase}" = "{bookcase}"
"{wheelbarrow}" = "{wheelbarrow}"
"{bookbinding}" = "{bookbinding}"
"{die}" = "{die}"
"{hive}" = "{hive}"
"{jug}" = "{jug}"
"{minecart}" = "{minecart}"
"{nestbox}" = "{nestbox}"
"{pedestal}" = "{pedestal}"
"{pot}" = "{pot}"
"{scrollroller}" = "{scrollroller}"
"{stepladder}" = "{stepladder}"
"{displaycase}" = "{displaycase}"
"{boltthrowerparts}" = "{boltthrowerparts}"

[[rulesets]]
name = "prefix::maybe_equipment_size"
optional = true
[rulesets.rules]
"small " = "작은 "
"large " = "큰 "
