base = "items::nestbox"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"nest box" = "둥지 상자"
"nest boxes" = "둥지 상자"