base = "items::orthopedic_cast"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"limb/body cast" = "사지/몸 깁스"
"limb/body casts" = "사지/몸 깁스"
