base = "items::pants"

[[rulesets]]
[rulesets.rules]
"{default}" = "{default}"
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "default"
[rulesets.rules]
"{::items::prefix::maybe_equipment_size}{default::^0}{default::main}" = "{::items::prefix::maybe_equipment_size}{default::^0}{default::main}"

[[rulesets]]
name = "default::^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "default::main"
[rulesets.rules]
"legwear" = "하의"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{^prefix}{::items::prefix::maybe_equipment_size}{^length}{^material}{^chain}{singular::main}" = "{^prefix}{::items::prefix::maybe_equipment_size}{^length}{^material}{^chain}{singular::main}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{^prefix}{::items::prefix::maybe_equipment_size}{^length}{^material}{^chain}{plural::main}" = "{^prefix}{::items::prefix::maybe_equipment_size}{^length}{^material}{^chain}{plural::main}"

[[rulesets]]
name = "^prefix"
optional = true
[rulesets.rules]
"pairs of " = ""

[[rulesets]]
name = "^length"
optional = true
[rulesets.rules]
"short " = "짧은"
"long " = "긴"

[[rulesets]]
name = "^material"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "^chain"
optional = true
[rulesets.rules]
"chain " = "사슬"

[[rulesets]]
name = "singular::main"
[rulesets.rules]
"trousers" = "긴바지"
"greaves" = "경갑"
"leggings" = "레깅스"
"loincloth" = "샅바"
"thong" = "팬티"
"skirt" = "치마"
"braies" = "반바지"

[[rulesets]]
name = "plural::main"
[rulesets.rules]
"trousers" = "긴바지"
"greaves" = "경갑"
"leggings" = "레깅스"
"loincloths" = "샅바"
"thongs" = "팬티"
"skirts" = "치마"
"braies" = "반바지"
