base = "items::plant_growth"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"withered " = "시든 "

[[rulesets]]
name = "main"
[rulesets.rules]
"{::plants::growth::singular}" = "{::plants::growth::singular}"
"{::plants::growth::plural}" = "{::plants::growth::plural}"
"leaf or fruit" = "잎과 열매"
"leaves and fruit" = "잎과 열매"
