base = "items::remains"

[[rulesets]]
[rulesets.rules]
"{^0}{^1}{main}" = "{^0}{^1}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"Rotten " = "썩은 "

[[rulesets]]
name = "^1"
optional = true
[rulesets.rules]
"{::creatures::name::singular} " = "{::creatures::name::singular}"

[[rulesets]]
name = "main"
[rulesets.rules]
"remains" = "유해"
"chunk" = "살덩이"
"chunks" = "살덩이"
