base = "items::shoes"

[[rulesets]]
[rulesets.rules]
"{::items::prefix::maybe_equipment_size}{main}" = "{::items::prefix::maybe_equipment_size}{main}"

[[rulesets]]
name = "main"
[rulesets.rules]
"{default}" = "{default}"
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "default"
[rulesets.rules]
"{default::^0}{default::main}" = "{default::^0}{default::main}"

[[rulesets]]
name = "default::^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "default::main"
[rulesets.rules]
"footwear" = "신발"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{^material}{^chain}{singular::main}" = "{^material}{^chain}{singular::main}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{^material}{^chain}{plural::main}" = "{^material}{^chain}{plural::main}"

[[rulesets]]
name = "^material"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "^chain"
optional = true
[rulesets.rules]
"chain " = "사슬"

[[rulesets]]
name = "singular::main"
[rulesets.rules]
"shoe" = "신발"
"high boot" = "롱부츠"
"low boot" = "앵클부츠"
"sandal" = "샌들"
"chausse" = "승마바지"
"sock" = "양말"

[[rulesets]]
name = "plural::main"
[rulesets.rules]
"shoes" = "신발"
"high boots" = "롱부츠"
"low boots" = "앵클부츠"
"sandals" = "샌들"
"chausses" = "승마바지"
"socks" = "양말"
