base = "items::slab"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"slab" = "석판"
"slabs" = "석판"
"memorial" = "기념비"
"memorials" = "기념비"
"craft shop sign" = "공예품 상점 간판"
"craft shop signs" = "공예품 상점 간판"
"weaponsmith's shop sign" = "무기 대장장이 상점 간판"
"weaponsmith's shop signs" = "무기 대장장이 상점 간판"
"armorsmith's shop sign" = "갑옷 대장장이 상점 간판"
"armorsmith's shop signs" = "갑옷 대장장이 상점 간판"
"general store sign" = "잡화 상점 간판"
"general store signs" = "잡화 상점 간판"
"food shop sign" = "식료품 상점 간판"
"food shop signs" = "식료품 상점 간판"
"food imports sign" = "식료품 수입 간판"
"food imports signs" = "식료품 수입 간판"
"clothing imports sign" = "의류 수입 간판"
"clothing imports signs" = "의류 수입 간판"
"general imports sign" = "잡화 수입 간판"
"general imports signs" = "잡화 수입 간판"
"cloth shop sign" = "의류 상점 간판"
"cloth shop signs" = "의류 상점 간판"
"leather shop sign" = "가죽 상점 간판"
"leather shop signs" = "가죽 상점 간판"
"woven clothing shop sign" = "직조 의류 상점 간판"
"woven clothing shop signs" = "직조 의류 상점 간판"
"leather clothing shop sign" = "가죽 의류 상점 간판"
"leather clothing shop signs" = "가죽 의류 상점 간판"
"bone carver's shop sign" = "뼈 조각사 상점 간판"
"bone carver's shop signs" = "뼈 조각사 상점 간판"
"gem cutter's shop sign" = "보석 세공사 상점 간판"
"gem cutter's shop signs" = "보석 세공사 상점 간판"
"bowyer's shop sign" = "활장이 상점 간판"
"bowyer's shop signs" = "활장이 상점 간판"
"blacksmith's shop sign" = "대장장이 상점 간판"
"blacksmith's shop signs" = "대장장이 상점 간판"
"metal craft shop sign" = "금속 공예 상점 간판"
"metal craft shop signs" = "금속 공예 상점 간판"
"leather goods shop sign" = "가죽 제품 상점 간판"
"leather goods shop signs" = "가죽 제품 상점 간판"
"carpenter's shop sign" = "목수 상점 간판"
"carpenter's shop signs" = "목수 상점 간판"
"stone furniture shop sign" = "석제 가구 상점 간판"
"stone furniture shop signs" = "석제 가구 상점 간판"
"metal furniture shop sign" = "금속 가구 상점 간판"
"metal furniture shop signs" = "금속 가구 상점 간판"
"tavern sign" = "주점 간판"
"tavern signs" = "주점 간판"
