base = "plants::seed"

[[rulesets]]
name = "plural"
[rulesets.rules]
"abaca seeds" = "아바카 씨앗"
"acacia seeds" = "아카시아 씨앗"
"acorns" = "도토리"
"alfalfa seeds" = "알팔파 씨앗"
"almonds" = "아몬드"
"apple seeds" = "사과 씨앗"
"apricot pits" = "살구 씨"
"artichoke seeds" = "아티초크 씨앗"
"asparagus seeds" = "아스파라거스 씨앗"
"avocado pits" = "아보카도 씨"
"bambara groundnuts" = "밤바라 땅콩"
"banana seeds" = "바나나 씨앗"
"barley seeds" = "보리 씨앗"
"bayberry seeds" = "양매 씨앗"
"beet seeds" = "비트 씨앗"
"bilberry seeds" = "빌베리 씨앗"
"bitter melon seeds" = "여주 씨앗"
"bitter orange seeds" = "쓴 오렌지 씨앗"
"bitter vetch seeds" = "쓴베치 씨앗"
"blackberry seeds" = "블랙베리 씨앗"
"blade weed seeds" = "칼날풀 씨앗"
"bloated tuber seeds" = "부푼 덩이뿌리 씨앗"
"blood amaranth seeds" = "피비름 씨앗"
"blueberry seeds" = "블루베리 씨앗"
"broad beans" = "잠두"
"buckwheat seeds" = "메밀 씨앗"
"cabbage seeds" = "양배추 씨앗"
"cacao beans" = "카카오 콩"
"candlenuts" = "캔들넛"
"caper seeds" = "케이퍼 씨앗"
"carambola seeds" = "카람볼라 씨앗"
"carrot seeds" = "당근 씨앗"
"cashews" = "캐슈넛"
"cassava seeds" = "카사바 씨앗"
"cave wheat seeds" = "동굴 밀 씨앗"
"celery seeds" = "샐러리 씨앗"
"cherry pits" = "체리 씨"
"chestnuts" = "밤"
"chickpeas" = "병아리콩"
"chicory seeds" = "치커리 씨앗"
"citron seeds" = "시트론 씨앗"
"coffee beans" = "커피콩"
"cotton seeds" = "목화 씨앗"
"cowpeas" = "동부콩"
"cranberry seeds" = "크랜베리 씨앗"
"cucumber seeds" = "오이 씨앗"
"custard-apple seeds" = "커스터드애플 씨앗"
"date palm seeds" = "대추야자 씨앗"
"desert lime seeds" = "사막 라임 씨앗"
"dimple cup spawn" = "오목컵버섯 종균"
"durian seeds" = "두리안 씨앗"
"eggplant seeds" = "가지 씨앗"
"elephant-head amaranth seeds" = "코끼리머리 아마란스 씨앗"
"finger lime seeds" = "핑거라임 씨앗"
"finger millet" = "손가락조"
"fisher berry seeds" = "피셔베리 씨앗"
"flax seeds" = "아마 씨앗"
"fonio" = "포니오"
"foxtail millet" = "조"
"garden cress seeds" = "가든 크레스 씨앗"
"garlic seeds" = "마늘 씨앗"
"ginkgo seeds" = "은행 씨앗"
"grape seeds" = "포도 씨앗"
"guava seeds" = "구아바 씨앗"
"hard wheat seeds" = "경질 밀 씨앗"
"hazel nuts" = "헤이즐넛"
"hemp seeds" = "대마 씨앗"
"hide root seeds" = "숨뿌리풀 씨앗"
"horned melon seeds" = "키와노 씨앗"
"jute seeds" = "황마 씨앗"
"kaniwa seeds" = "카니와 씨앗"
"kenaf seeds" = "케나프 씨앗"
"kumquat seeds" = "금귤 씨앗"
"leek seeds" = "리크 씨앗"
"lentils" = "렌틸콩"
"lesser yam seeds" = "작은 얌 씨앗"
"lettuce seeds" = "상추 씨앗"
"lime seeds" = "라임 씨앗"
"Longland grass seeds" = "롱랜드 풀 씨앗"
"long yam seeds" = "긴 얌 씨앗"
"lychee seeds" = "리치 씨앗"
"macadamia nuts" = "마카다미아 견과"
"maize" = "옥수수"
"mango pits" = "망고 씨"
"muck root seeds" = "진흙뿌리 씨앗"
"mung beans" = "녹두"
"muskmelon seeds" = "머스크멜론 씨앗"
"oat seeds" = "귀리 씨앗"
"olive pits" = "올리브 씨"
"onion seeds" = "양파 씨앗"
"orange seeds" = "오렌지 씨앗"
"papaya seeds" = "파파야 씨앗"
"papyrus seeds" = "파피루스 씨앗"
"paradise nuts" = "파라다이스 너트"
"parsnip seeds" = "파스닙 씨앗"
"passion fruit seeds" = "패션프루트 씨앗"
"peach pits" = "복숭아 씨"
"peanuts" = "땅콩"
"pearl millet" = "진주조"
"pear seeds" = "배 씨앗"
"peas" = "완두콩"
"pecans" = "피칸"
"pendant amaranth seeds" = "꼬리비름 씨앗"
"pepper seeds" = "후추 씨앗"
"persimmon seeds" = "감 씨앗"
"pig tail seeds" = "돼지꼬리풀 씨앗"
"pineapple seeds" = "파인애플 씨앗"
"plump helmet spawn" = "통통투구버섯 종균"
"plum pits" = "자두 씨"
"pomegranate seeds" = "석류 씨앗"
"pomelo seeds" = "포멜로 씨앗"
"potato seeds" = "감자 씨앗"
"prickle berry seeds" = "가시베리 씨앗"
"purple amaranth seeds" = "자색 비름 씨앗"
"purple yam seeds" = "자색 얌 씨앗"
"quinoa seeds" = "퀴노아 씨앗"
"radish seeds" = "래디시 씨앗"
"rambutan seeds" = "람부탄 씨앗"
"ramie seeds" = "모시풀 씨앗"
"raspberry seeds" = "라즈베리 씨앗"
"rat weed seeds" = "쥐잡초 씨앗"
"red beans" = "팥"
"red spinach seeds" = "붉은 시금치 씨앗"
"rhubarb seeds" = "대황 씨앗"
"rice" = "쌀"
"rock nuts" = "바위 견과"
"rope reed seeds" = "밧줄갈대 씨앗"
"round lime seeds" = "둥근 라임 씨앗"
"rye seeds" = "호밀 씨앗"
"sand pear seeds" = "모래배 씨앗"
"single-grain wheat seeds" = "단립밀 씨앗"
"sliver barb seeds" = "갈라진 갈고리풀 씨앗"
"soft wheat seeds" = "연질밀 씨앗"
"sorghum seeds" = "수수 씨앗"
"soybeans" = "대두"
"spelt seeds" = "스펠트밀 씨앗"
"spinach seeds" = "시금치 씨앗"
"squash seeds" = "주키니 씨앗"
"strawberry seeds" = "딸기 씨앗"
"string beans" = "스트링빈"
"sun berry seeds" = "태양베리 씨앗"
"sweet pod seeds" = "달콤한 꼬투리 씨앗"
"sweet potato seeds" = "고구마 씨앗"
"taro seeds" = "토란 씨앗"
"tea seeds" = "차 씨앗"
"teff" = "테프"
"tomatillo seeds" = "토마틸로 씨앗"
"tomato seeds" = "토마토 씨앗"
"turnip seeds" = "순무 씨앗"
"two-grain wheat seeds" = "이립밀 씨앗"
"urad beans" = "우라드콩"
"walnuts" = "호두"
"watermelon seeds" = "수박 씨앗"
"whip vine seeds" = "채찍덩굴 씨앗"
"white millet" = "흰기장"
"white yam seeds" = "흰 얌 씨앗"
"winter melon seeds" = "동아 씨앗"
