base = "gems"

[[rulesets]]
[rulesets.rules]
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{materials::singular}" = "{materials::singular}"
"{::materials}" = "{::materials}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{materials::plural}" = "{materials::plural}"
"{::materials}" = "{::materials}"

[[rulesets]]
name = "materials::singular"
[rulesets.rules]
"onyx" = "오닉스"
"morion" = "흑수정"
"schorl" = "흑전기석"
"lace agate" = "레이스 마노"
"blue jade" = "파란 비취"
"lapis lazuli" = "청금석"
"prase" = "창록 석영"
"prase opal" = "창록 오팔"
"bloodstone" = "혈석"
"moss agate" = "이끼 마노"
"moss opal" = "이끼 오팔"
"variscite" = "인알루미늄석"
"chrysoprase" = "녹옥수"
"chrysocolla" = "규공작석"
"sard" = "갈옥수"
"carnelian" = "홍옥수"
"banded agate" = "띠무늬 마노"
"sardonyx" = "사도닉스"
"cherry opal" = "체리 오팔"
"lavender jade" = "라벤더 비취"
"pink jade" = "분홍 비취"
"tube agate" = "관맥 마노"
"fire agate" = "불 마노"
"plume agate" = "깃털 마노"
"brown jasper" = "갈색 벽옥"
"picture jasper" = "그림 벽옥"
"smoky quartz" = "연수정"
"wax opal" = "왁스 오팔"
"wood opal" = "나무 오팔"
"amber opal" = "호박 오팔"
"gold opal" = "금 오팔"
"citrine" = "황수정"
"yellow jasper" = "노란 벽옥"
"tigereye" = "호안석"
"tiger iron" = "호철석"
"sunstone" = "일장석"
"resin opal" = "수지 오팔"
"pyrite" = "황철석"
"clear tourmaline" = "투명 전기석"
"gray chalcedony" = "회옥수"
"dendritic agate" = "가지무늬 마노"
"shell opal" = "조개 오팔"
"bone opal" = "골질 오팔"
"white chalcedony" = "백옥수"
"fortification agate" = "성곽마노"
"milk quartz" = "유백석영"
"moonstone" = "월장석"
"white jade" = "백비취"
"jasper opal" = "벽옥오팔"
"pineapple opal" = "파인애플오팔"
"onyx opal" = "오닉스오팔"
"milk opal" = "유백오팔"
"pipe opal" = "파이프오팔"
"aventurine" = "사금석"
"turquoise" = "터키석"
"rose quartz" = "장미석영"
"rock crystal" = "암수정"
"black zircon" = "검은지르콘"
"black pyrope" = "검은파이로프"
"melanite" = "멜라나이트"
"indigo tourmaline" = "남색토르말린"
"blue garnet" = "파란가넷"
"tsavorite" = "차보라이트"
"green tourmaline" = "녹색토르말린"
"demantoid" = "데만토이드"
"green zircon" = "녹색지르콘"
"green jade" = "녹비취"
"heliodor" = "헬리오도르"
"peridot" = "감람석"
"red zircon" = "붉은지르콘"
"red tourmaline" = "붉은토르말린"
"red pyrope" = "붉은파이로프"
"almandine" = "알만딘"
"red grossular" = "붉은그로슐라"
"pink tourmaline" = "분홍토르말린"
"red beryl" = "붉은베릴"
"fire opal" = "파이어오팔"
"rhodolite" = "로돌라이트"
"purple spinel" = "보라색스피넬"
"alexandrite" = "알렉산드라이트"
"tanzanite" = "탄자나이트"
"morganite" = "모르가나이트"
"violet spessartine" = "보라색스페서타인"
"pink garnet" = "분홍가넷"
"kunzite" = "쿤자이트"
"cinnamon grossular" = "시나몬그로슐라"
"honey yellow beryl" = "꿀노란베릴"
"jelly opal" = "젤리오팔"
"brown zircon" = "갈색지르콘"
"yellow zircon" = "노란지르콘"
"golden beryl" = "황금베릴"
"yellow spessartine" = "노란스페서타인"
"topaz" = "토파즈"
"topazolite" = "토파졸라이트"
"yellow grossular" = "노란 그로슐라"
"rubicelle" = "주황색 스피넬"
"clear garnet" = "투명 석류석"
"goshenite" = "고셰나이트"
"cat's eye" = "묘안석"
"clear zircon" = "투명 지르콘"
"amethyst" = "자수정"
"aquamarine" = "아쿠아마린"
"red spinel" = "붉은 스피넬"
"chrysoberyl" = "크리소베릴"
"precious fire opal" = "귀한 파이어 오팔"
"red flash opal" = "붉은 플래시 오팔"
"black opal" = "검은 오팔"
"white opal" = "흰 오팔"
"crystal opal" = "크리스탈 오팔"
"claro opal" = "스모키 오팔"
"levin opal" = "뇌전 오팔"
"harlequin opal" = "할리퀸 오팔"
"pinfire opal" = "핀파이어 오팔"
"bandfire opal" = "밴드파이어 오팔"
"light yellow diamond" = "밝은 노란 다이아몬드"
"faint yellow diamond" = "옅은 노란 다이아몬드"
"emerald" = "에메랄드"
"ruby" = "루비"
"sapphire" = "사파이어"
"clear diamond" = "무색 다이아몬드"
"red diamond" = "붉은 다이아몬드"
"green diamond" = "초록 다이아몬드"
"blue diamond" = "파란 다이아몬드"
"yellow diamond" = "노란 다이아몬드"
"black diamond" = "검은 다이아몬드"
"star sapphire" = "스타 사파이어"
"star ruby" = "스타 루비"

[[rulesets]]
name = "materials::plural"
[rulesets.rules]
"onyxes" = "오닉스"
"morions" = "흑수정"
"schorls" = "흑전기석"
"lace agates" = "레이스 마노"
"blue jades" = "파란 비취"
"lapis lazulis" = "청금석"
"prases" = "프라세"
"prase opals" = "프라세 오팔"
"bloodstones" = "혈석"
"moss agates" = "이끼 마노"
"moss opals" = "이끼 오팔"
"variscites" = "바리사이트"
"chrysoprases" = "녹옥수"
"chrysocollas" = "규공작석"
"sards" = "갈옥수"
"carnelians" = "홍옥수"
"banded agates" = "줄무늬 마노"
"sardonyxes" = "사도닉스"
"cherry opals" = "체리 오팔"
"lavender jades" = "라벤더 비취"
"pink jades" = "분홍 비취"
"tube agates" = "관형 마노"
"fire agates" = "화염 마노"
"plume agates" = "깃털 마노"
"brown jaspers" = "갈색 벽옥"
"picture jaspers" = "그림 벽옥"
"smoky quartzes" = "연수정"
"wax opals" = "밀랍질 오팔"
"wood opals" = "목질 오팔"
"amber opals" = "호박 오팔"
"gold opals" = "금색 오팔"
"citrines" = "황수정"
"yellow jaspers" = "노란 벽옥"
"tigereyes" = "호안석"
"tiger irons" = "타이거 아이언"
"sunstones" = "일장석"
"resin opals" = "수지 오팔"
"pyrites" = "황철석"
"clear tourmalines" = "투명 토르말린"
"gray chalcedonies" = "회색 옥수"
"dendritic agates" = "가지무늬 마노"
"shell opals" = "조개 오팔"
"bone opals" = "골질 오팔"
"white chalcedonies" = "흰 옥수"
"fortification agates" = "성벽 마노"
"milk quartzes" = "유백수정"
"moonstones" = "월장석"
"white jades" = "흰 비취"
"jasper opals" = "벽옥 오팔"
"pineapple opals" = "파인애플 오팔"
"onyx opals" = "오닉스 오팔"
"milk opals" = "유백 오팔"
"pipe opals" = "관무늬 오팔"
"aventurines" = "사금석"
"turquoises" = "터키석"
"rose quartzes" = "장미수정"
"rock crystals" = "암석 수정"
"black zircons" = "검은 지르콘"
"black pyropes" = "검은 파이로프"
"melanites" = "멜라나이트"
"indigo tourmalines" = "남색 토르말린"
"blue garnets" = "파란 석류석"
"tsavorites" = "차보라이트"
"green tourmalines" = "녹색 토르말린"
"demantoids" = "데만토이드"
"green zircons" = "녹색 지르콘"
"green jades" = "녹색 비취"
"heliodors" = "헬리오도르"
"peridots" = "페리도트"
"red zircons" = "붉은 지르콘"
"red tourmalines" = "붉은 토르말린"
"red pyropes" = "붉은 파이로프"
"almandines" = "알만딘"
"red grossulars" = "붉은 그로슐라"
"pink tourmalines" = "분홍 토르말린"
"red beryls" = "붉은 베릴"
"fire opals" = "파이어 오팔"
"rhodolites" = "로돌라이트"
"purple spinels" = "보라색 스피넬"
"alexandrites" = "알렉산드라이트"
"tanzanites" = "탄자나이트"
"morganites" = "모거나이트"
"violet spessartines" = "보라색 스페서타인"
"pink garnets" = "분홍 가넷"
"kunzites" = "쿤자이트"
"cinnamon grossulars" = "계피색 그로슐라"
"honey yellow beryls" = "꿀빛 베릴"
"jelly opals" = "젤리 오팔"
"brown zircons" = "갈색 지르콘"
"yellow zircons" = "노란 지르콘"
"golden beryls" = "금빛 베릴"
"yellow spessartines" = "주황색 스페서타인"
"topazes" = "토파즈"
"topazolites" = "토파졸라이트"
"yellow grossulars" = "노란 그로슐라"
"rubicelles" = "주황색 스피넬"
"clear garnets" = "투명 가넷"
"goshenites" = "고셰나이트"
"cat's eyes" = "캣츠아이"
"clear zircons" = "투명 지르콘"
"amethysts" = "자수정"
"aquamarines" = "아쿠아마린"
"red spinels" = "붉은 스피넬"
"chrysoberyls" = "크리소베릴"
"precious fire opals" = "진귀한 파이어 오팔"
"red flash opals" = "붉은 섬광 오팔"
"black opals" = "검은 오팔"
"white opals" = "흰 오팔"
"crystal opals" = "크리스탈 오팔"
"claro opals" = "연기 오팔"
"levin opals" = "번개 오팔"
"harlequin opals" = "할리퀸 오팔"
"pinfire opals" = "핀파이어 오팔"
"bandfire opals" = "밴드파이어 오팔"
"light yellow diamonds" = "밝은 노란 다이아몬드"
"faint yellow diamonds" = "연한 노란 다이아몬드"
"emeralds" = "에메랄드"
"rubies" = "루비"
"sapphires" = "사파이어"
"clear diamonds" = "투명 다이아몬드"
"red diamonds" = "빨간 다이아몬드"
"green diamonds" = "녹색 다이아몬드"
"blue diamonds" = "파란 다이아몬드"
"yellow diamonds" = "노란 다이아몬드"
"black diamonds" = "검은 다이아몬드"
"star sapphires" = "스타 사파이어"
"star rubies" = "스타 루비"
